TilesetKantoPalMap:
	tilepal GRAY, BROWN, BROWN, RED, BROWN, ROOF, ROOF, ROOF
	tilepal ROOF, ROOF, YELLOW, YELLOW, YELLOW, GRAY, BROWN, GRAY
	tilepal GRAY, BROWN, ROOF, BROWN, WATER, ROOF, ROOF, ROOF
	tilepal ROOF, ROOF, GRAY, BROWN, BROWN, GRAY, BROWN, GRAY
	tilepal GRAY, GRAY, GRAY, GRAY, BROWN, ROOF, ROOF, BROWN
	tilepal ROOF, ROOF, GRAY, GRAY, GREEN, GREEN, GREEN, GRAY
	tilepal BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN
	tilepal ROOF, GRAY, GRAY, GRAY, GRAY, GREEN, GREEN, GRAY
	tilepal GREEN, GREEN, GRAY, GRAY, GRAY, GRAY, BROWN, BROWN
	tilepal BROWN, BROWN, GRAY, BROWN, GRAY, GRAY, GRAY, RED
	tilepal GREEN, GREEN, GREEN, ROOF, BROWN, BROWN, BROWN, BROWN
	tilepal BROWN, BROWN, GRAY, BROWN, GRAY, GRAY, GRAY, GRAY

Tileset0PalMap:
TilesetJohtoPalMap:
	tilepal GRAY, BROWN, BROWN, RED, GREEN, GREEN, GRAY, RED
	tilepal RED, RED, ROOF, ROOF, ROOF, ROOF, ROOF, ROOF
	tilepal ROOF, ROOF, ROOF, GREEN, WATER, GREEN, BROWN, BROWN
	tilepal RED, RED, BROWN, BROWN, BROWN, GREEN, GREEN, GREEN
	tilepal BROWN, BROWN, BROWN, RED, RED, BROWN, YELLOW, BROWN
	tilepal BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, GREEN, GREEN
	tilepal BROWN, BROWN, WATER, WATER, BROWN, BROWN, BROWN, YELLOW
	tilepal YELLOW, BROWN, BROWN, BROWN, BROWN, BROWN, GREEN, GREEN
	tilepal RED, BROWN, WATER, WATER, BROWN, GREEN, BROWN, BROWN
	tilepal BROWN, WATER, GRAY, BROWN, BROWN, BROWN, GRAY, GRAY
	tilepal BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN
	tilepal WATER, GRAY, GRAY, GRAY, BROWN, BROWN, GRAY, GRAY

TilesetJohtoModernPalMap:
	tilepal GRAY, BROWN, BROWN, RED, GREEN, GREEN, GRAY, ROOF
	tilepal RED, RED, ROOF, ROOF, ROOF, ROOF, ROOF, ROOF
	tilepal ROOF, ROOF, ROOF, GREEN, WATER, GREEN, BROWN, BROWN
	tilepal RED, RED, BROWN, BROWN, BROWN, GRAY, GREEN, GREEN
	tilepal GRAY, GRAY, BROWN, RED, RED, GRAY, YELLOW, BROWN
	tilepal BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, GRAY, RED
	tilepal GRAY, BROWN, BROWN, GRAY, BROWN, GRAY, GRAY, YELLOW
	tilepal YELLOW, BROWN, BROWN, BROWN, BROWN, BROWN, GREEN, GREEN
	tilepal RED, BROWN, GRAY, GRAY, BROWN, BROWN, BROWN, BROWN
	tilepal BROWN, WATER, GRAY, BROWN, BROWN, BROWN, GRAY, GRAY
	tilepal GRAY, BROWN, BROWN, GRAY, BROWN, GRAY, GRAY, GRAY
	tilepal WATER, GRAY, GRAY, GRAY, BROWN, BROWN, GRAY, GRAY

TilesetHousePalMap:
	tilepal WATER, RED, RED, RED, RED, BROWN, WATER, WATER
	tilepal GREEN, GREEN, GREEN, GREEN, WATER, WATER, BROWN, BROWN
	tilepal BROWN, BROWN, RED, RED, RED, BROWN, WATER, WATER
	tilepal BROWN, BROWN, BROWN, BROWN, GRAY, GRAY, BROWN, BROWN
	tilepal GRAY, GRAY, BROWN, BROWN, WATER, BROWN, BROWN, BROWN
	tilepal BROWN, BROWN, YELLOW, GREEN, WATER, WATER, WATER, BROWN
	tilepal BROWN, BROWN, BROWN, BROWN, WATER, BROWN, BROWN, BROWN
	tilepal BROWN, BROWN, BROWN, BROWN, BROWN, WATER, WATER, BROWN
	tilepal GRAY, GRAY, BROWN, BROWN, WATER, WATER, BROWN, BROWN
	tilepal GRAY, GRAY, WATER, GRAY, BROWN, BROWN, BROWN, WATER
	tilepal RED, RED, BROWN, BROWN, GREEN, YELLOW, BROWN, BROWN
	tilepal GRAY, GRAY, GRAY, GRAY, BROWN, BROWN, BROWN, BROWN

TilesetPlayersHousePalMap:
	tilepal GRAY, BROWN, BROWN, BROWN, RED, GREEN, WATER, WATER
	tilepal BROWN, BROWN, GRAY, GRAY, GRAY, GRAY, BROWN, BROWN
	tilepal BROWN, BROWN, BROWN, BROWN, RED, BROWN, WATER, WATER
	tilepal BROWN, BROWN, GRAY, GRAY, BROWN, BROWN, BROWN, BROWN
	tilepal GRAY, GRAY, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN
	tilepal GRAY, GRAY, GRAY, GRAY, WATER, WATER, BROWN, BROWN
	tilepal GRAY, GRAY, BROWN, BROWN, BROWN, BROWN, GRAY, GRAY
	tilepal GRAY, GRAY, BROWN, BROWN, WATER, WATER, BROWN, BROWN
	tilepal BROWN, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY
	tilepal GRAY, GRAY, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN
	tilepal GRAY, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY
	tilepal GRAY, GRAY, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN

TilesetPokecenterPalMap:
	tilepal GRAY, RED, GRAY, WATER, WATER, WATER, ROOF, ROOF
	tilepal GRAY, GRAY, GRAY, GRAY, GRAY, WATER, WATER, WATER
	tilepal GRAY, RED, RED, WATER, WATER, WATER, WATER, WATER
	tilepal GRAY, GRAY, GRAY, GRAY, GRAY, GREEN, GREEN, GRAY
	tilepal GRAY, GRAY, RED, RED, WATER, WATER, GRAY, GRAY
	tilepal GRAY, GRAY, BROWN, BROWN, GRAY, GRAY, GRAY, GRAY
	tilepal GRAY, GRAY, RED, RED, GRAY, WATER, WATER, WATER
	tilepal WATER, WATER, WATER, WATER, GRAY, GRAY, WATER, GRAY
	tilepal GRAY, GRAY, RED, RED, RED, RED, WATER, WATER
	tilepal YELLOW, YELLOW, GRAY, GRAY, GRAY, RED, RED, GRAY
	tilepal RED, RED, RED, RED, RED, RED, GRAY, GRAY
	tilepal YELLOW, YELLOW, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY

TilesetGatePalMap:
	tilepal GRAY, GRAY, WATER, WATER, RED, GREEN, GREEN, GREEN
	tilepal GREEN, GREEN, GRAY, GRAY, GRAY, GRAY, GREEN, GREEN
	tilepal WATER, GRAY, WATER, WATER, RED, BROWN, BROWN, WATER
	tilepal GREEN, GREEN, GRAY, GRAY, GRAY, GRAY, BROWN, WATER
	tilepal GREEN, GREEN, GRAY, GRAY, GREEN, GREEN, WATER, WATER
	tilepal RED, RED, GREEN, GREEN, GREEN, GREEN, GREEN, GREEN
	tilepal GREEN, GREEN, GREEN, GREEN, GRAY, WATER, WATER, WATER
	tilepal GREEN, GREEN, GREEN, GREEN, GREEN, GREEN, GRAY, GRAY
	tilepal GRAY, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY
	tilepal GRAY, GRAY, GRAY, GRAY, GRAY, GRAY, WATER, WATER
	tilepal GRAY, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY
	tilepal GRAY, GRAY, GRAY, GRAY, WATER, WATER, GRAY, GRAY

TilesetPortPalMap:
	tilepal GRAY, WATER, WATER, GRAY, GRAY, RED, BROWN, BROWN
	tilepal BROWN, BROWN, GRAY, GRAY, RED, RED, RED, BROWN
	tilepal ROOF, WATER, WATER, WATER, WATER, RED, BROWN, BROWN
	tilepal BROWN, BROWN, ROOF, WATER, RED, RED, GRAY, GRAY
	tilepal BROWN, BROWN, BROWN, ROOF, ROOF, ROOF, ROOF, ROOF
	tilepal ROOF, ROOF, ROOF, ROOF, RED, ROOF, ROOF, ROOF
	tilepal ROOF, GRAY, ROOF, ROOF, ROOF, ROOF, ROOF, ROOF
	tilepal ROOF, ROOF, ROOF, ROOF, ROOF, ROOF, ROOF, ROOF
	tilepal ROOF, ROOF, ROOF, ROOF, ROOF, ROOF, ROOF, ROOF
	tilepal ROOF, ROOF, ROOF, ROOF, ROOF, ROOF, ROOF, ROOF
	tilepal ROOF, ROOF, ROOF, ROOF, ROOF, ROOF, ROOF, ROOF
	tilepal ROOF, ROOF, ROOF, ROOF, ROOF, ROOF, ROOF, ROOF

TilesetLabPalMap:
	tilepal GRAY, WATER, RED, BROWN, BROWN, BROWN, BROWN, BROWN
	tilepal WATER, WATER, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY
	tilepal GRAY, WATER, RED, BROWN, BROWN, BROWN, BROWN, BROWN
	tilepal WATER, WATER, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY
	tilepal WATER, WATER, WATER, WATER, ROOF, BROWN, BROWN, BROWN
	tilepal RED, RED, BROWN, BROWN, BROWN, GREEN, GREEN, GREEN
	tilepal WATER, WATER, WATER, WATER, RED, BROWN, BROWN, GRAY
	tilepal RED, RED, BROWN, BROWN, BROWN, GREEN, GREEN, GREEN
	tilepal ROOF, ROOF, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY
	tilepal GRAY, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY
	tilepal ROOF, ROOF, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY
	tilepal GRAY, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY

TilesetFacilityPalMap:
	tilepal GRAY, WATER, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN
	tilepal BROWN, BROWN, GRAY, GRAY, RED, RED, BROWN, BROWN
	tilepal ROOF, ROOF, BROWN, BROWN, BROWN, BROWN, GRAY, GRAY
	tilepal ROOF, ROOF, GRAY, GRAY, ROOF, ROOF, BROWN, BROWN
	tilepal ROOF, ROOF, GREEN, WATER, WATER, WATER, RED, RED
	tilepal BROWN, BROWN, BROWN, BROWN, GREEN, GREEN, BROWN, BROWN
	tilepal ROOF, ROOF, GREEN, GREEN, RED, RED, GRAY, RED
	tilepal RED, RED, BROWN, BROWN, GREEN, GREEN, BROWN, BROWN
	tilepal BROWN, BROWN, BROWN, GREEN, GREEN, GRAY, BROWN, WATER
	tilepal BROWN, BROWN, GRAY, BROWN, BROWN, BROWN, BROWN, GRAY
	tilepal BROWN, BROWN, BROWN, BROWN, BROWN, GRAY, BROWN, ROOF
	tilepal ROOF, ROOF, GRAY, BROWN, GRAY, GRAY, GRAY, GRAY

TilesetMartPalMap:
	tilepal GRAY, YELLOW, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY
	tilepal GREEN, GREEN, WATER, RED, GRAY, GRAY, ROOF, ROOF
	tilepal GRAY, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY
	tilepal BROWN, BROWN, BROWN, RED, ROOF, ROOF, GRAY, YELLOW
	tilepal GRAY, GRAY, RED, RED, RED, RED, WATER, WATER
	tilepal WATER, WATER, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY
	tilepal GRAY, GRAY, RED, RED, RED, RED, WATER, WATER
	tilepal WATER, WATER, RED, GRAY, GRAY, GRAY, GRAY, GRAY
	tilepal GRAY, GRAY, GRAY, GRAY, GRAY, RED, RED, RED
	tilepal GREEN, GRAY, GREEN, GREEN, GRAY, GRAY, GRAY, GRAY
	tilepal GRAY, GRAY, RED, YELLOW, YELLOW, YELLOW, ROOF, ROOF
	tilepal ROOF, ROOF, ROOF, ROOF, RED, RED, BROWN, BROWN

TilesetMansionPalMap:
	tilepal GRAY, BROWN, WATER, ROOF, RED, ROOF, BROWN, BROWN
	tilepal GRAY, GRAY, GRAY, GRAY, ROOF, ROOF, ROOF, ROOF
	tilepal GRAY, RED, ROOF, ROOF, ROOF, ROOF, BROWN, BROWN
	tilepal GRAY, GRAY, GRAY, GRAY, ROOF, ROOF, ROOF, ROOF
	tilepal GRAY, GRAY, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN
	tilepal RED, GRAY, BROWN, BROWN, BROWN, BROWN, GREEN, GREEN
	tilepal GRAY, GRAY, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN
	tilepal BROWN, GRAY, BROWN, BROWN, BROWN, BROWN, GREEN, GREEN
	tilepal GRAY, GRAY, GRAY, GRAY, GRAY, ROOF, BROWN, BROWN
	tilepal BROWN, GRAY, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN
	tilepal GRAY, GRAY, GRAY, GRAY, GRAY, ROOF, BROWN, BROWN
	tilepal BROWN, GRAY, BROWN, BROWN, ROOF, ROOF, BROWN, BROWN

TilesetGameCornerPalMap:
	tilepal GRAY, RED, BROWN, RED, ROOF, ROOF, GREEN, GREEN
	tilepal GREEN, GREEN, RED, RED, RED, RED, ROOF, BROWN
	tilepal RED, RED, RED, RED, ROOF, ROOF, GRAY, GRAY
	tilepal GRAY, GREEN, RED, RED, RED, RED, ROOF, ROOF
	tilepal BROWN, BROWN, RED, RED, BROWN, BROWN, GRAY, GRAY
	tilepal GRAY, GREEN, RED, RED, GREEN, GRAY, RED, RED
	tilepal BROWN, BROWN, RED, RED, RED, RED, BROWN, BROWN
	tilepal BROWN, BROWN, RED, RED, GREEN, ROOF, RED, RED
	tilepal ROOF, ROOF, GRAY, GRAY, GRAY, GRAY, RED, RED
	tilepal GRAY, GRAY, GRAY, GRAY, GRAY, ROOF, RED, RED
	tilepal RED, GRAY, GRAY, GRAY, GRAY, GRAY, RED, RED
	tilepal GRAY, GRAY, GRAY, WATER, ROOF, ROOF, WATER, WATER

TilesetEliteFourRoomPalMap:
	tilepal GRAY, ROOF, RED, RED, RED, ROOF, ROOF, GREEN
	tilepal GREEN, GRAY, GREEN, GREEN, GREEN, GREEN, WATER, GREEN
	tilepal GRAY, WATER, WATER, WATER, RED, ROOF, ROOF, BROWN
	tilepal BROWN, RED, GRAY, GREEN, GREEN, GREEN, GREEN, GREEN
	tilepal RED, RED, GRAY, GRAY, WATER, GRAY, GRAY, GRAY
	tilepal GRAY, RED, GRAY, GRAY, GRAY, ROOF, GREEN, BROWN
	tilepal RED, RED, GRAY, GRAY, WATER, GRAY, GRAY, GRAY
	tilepal RED, WATER, GRAY, GRAY, GRAY, GRAY, RED, RED
	tilepal GRAY, GRAY, GRAY, GRAY, GRAY, BROWN, BROWN, BROWN
	tilepal WATER, WATER, WATER, WATER, WATER, WATER, ROOF, ROOF
	tilepal WATER, GREEN, GREEN, BROWN, GRAY, GRAY, GRAY, GRAY
	tilepal GRAY, GRAY, WATER, RED, WATER, WATER, ROOF, ROOF

TilesetTraditionalHousePalMap:
	tilepal GRAY, BROWN, WATER, WATER, RED, GRAY, GRAY, GRAY
	tilepal BROWN, BROWN, GRAY, GRAY, BROWN, BROWN, BROWN, BROWN
	tilepal BROWN, BROWN, WATER, WATER, RED, BROWN, GRAY, GRAY
	tilepal BROWN, BROWN, GRAY, GRAY, BROWN, BROWN, BROWN, BROWN
	tilepal GRAY, GRAY, BROWN, BROWN, BROWN, BROWN, BROWN, GRAY
	tilepal GRAY, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN
	tilepal GRAY, GRAY, BROWN, BROWN, BROWN, BROWN, RED, GRAY
	tilepal GRAY, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN
	tilepal BROWN, BROWN, BROWN, BROWN, GREEN, GREEN, GREEN, BROWN
	tilepal BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, WATER, WATER
	tilepal BROWN, BROWN, BROWN, BROWN, GREEN, GREEN, GREEN, BROWN
	tilepal BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, WATER, BROWN

TilesetTowerPalMap:
	tilepal BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, RED
	tilepal RED, RED, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN
	tilepal BROWN, BROWN, GRAY, GRAY, BROWN, BROWN, BROWN, RED
	tilepal RED, RED, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN
	tilepal BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, GRAY, GRAY
	tilepal RED, RED, GRAY, GRAY, BROWN, BROWN, BROWN, BROWN
	tilepal BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, GRAY, GRAY
	tilepal RED, RED, GRAY, GRAY, BROWN, BROWN, BROWN, BROWN
	tilepal BROWN, BROWN, YELLOW, YELLOW, BROWN, BROWN, BROWN, BROWN
	tilepal BROWN, BROWN, YELLOW, YELLOW, YELLOW, BROWN, BROWN, BROWN
	tilepal BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN
	tilepal BROWN, BROWN, YELLOW, YELLOW, YELLOW, BROWN, BROWN, BROWN

TilesetCavePalMap:
TilesetDarkCavePalMap:
	tilepal BROWN, BROWN, GRAY, GRAY, GREEN, BROWN, BROWN, BROWN
	tilepal GRAY, GRAY, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN
	tilepal BROWN, BROWN, GRAY, GRAY, WATER, BROWN, BROWN, BROWN
	tilepal GRAY, GRAY, YELLOW, YELLOW, BROWN, BROWN, BROWN, BROWN
	tilepal BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN
	tilepal BROWN, BROWN, BROWN, BROWN, GRAY, GRAY, GRAY, GRAY
	tilepal BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, GRAY, GRAY
	tilepal BROWN, BROWN, BROWN, BROWN, GRAY, GRAY, GRAY, GRAY
	tilepal WATER, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY
	tilepal GRAY, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY
	tilepal GRAY, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY
	tilepal GRAY, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY

TilesetParkPalMap:
	tilepal GRAY, GREEN, BROWN, RED, GREEN, BROWN, GRAY, GRAY
	tilepal GRAY, GRAY, GRAY, GRAY, GREEN, GREEN, GREEN, GREEN
	tilepal RED, RED, RED, GRAY, WATER, ROOF, GRAY, GRAY
	tilepal GRAY, GRAY, GRAY, BROWN, GREEN, GREEN, GREEN, GREEN
	tilepal RED, RED, RED, BROWN, BROWN, BROWN, BROWN, GRAY
	tilepal GRAY, GRAY, GRAY, BROWN, GREEN, BROWN, BROWN, GREEN
	tilepal RED, RED, RED, BROWN, BROWN, BROWN, BROWN, BROWN
	tilepal BROWN, BROWN, GREEN, GREEN, GREEN, BROWN, BROWN, GREEN
	tilepal BROWN, RED, BROWN, BROWN, GRAY, GRAY, GRAY, BROWN
	tilepal BROWN, BROWN, GREEN, GREEN, WATER, WATER, WATER, RED
	tilepal BROWN, BROWN, BROWN, BROWN, GRAY, GRAY, GRAY, BROWN
	tilepal BROWN, BROWN, GRAY, GRAY, WATER, WATER, WATER, GRAY

TilesetRuinsOfAlphPalMap:
	tilepal GRAY, GRAY, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN
	tilepal WATER, WATER, WATER, WATER, YELLOW, YELLOW, GRAY, GRAY
	tilepal YELLOW, YELLOW, BROWN, BROWN, YELLOW, YELLOW, YELLOW, YELLOW
	tilepal YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, GRAY, GRAY
	tilepal YELLOW, YELLOW, YELLOW, YELLOW, BROWN, BROWN, BROWN, BROWN
	tilepal BROWN, BROWN, RED, RED, RED, GRAY, GRAY, GRAY
	tilepal YELLOW, YELLOW, YELLOW, YELLOW, BROWN, BROWN, YELLOW, YELLOW
	tilepal YELLOW, YELLOW, RED, RED, RED, GRAY, GRAY, GRAY
	tilepal YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW
	tilepal YELLOW, YELLOW, YELLOW, YELLOW, GRAY, GRAY, GRAY, GRAY
	tilepal GRAY, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY
	tilepal GRAY, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY

TilesetRadioTowerPalMap:
	tilepal GRAY, RED, RED, WATER, WATER, GRAY, GRAY, GRAY
	tilepal GRAY, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY
	tilepal WATER, WATER, RED, WATER, WATER, GRAY, GRAY, GRAY
	tilepal GRAY, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY
	tilepal ROOF, ROOF, GRAY, GRAY, WATER, GRAY, GRAY, BROWN
	tilepal BROWN, ROOF, ROOF, GRAY, RED, RED, GRAY, GRAY
	tilepal GRAY, GRAY, GRAY, GRAY, WATER, GRAY, GRAY, BROWN
	tilepal BROWN, GRAY, GRAY, GRAY, RED, RED, GRAY, GRAY
	tilepal GRAY, GRAY, BROWN, BROWN, GRAY, GRAY, GREEN, GREEN
	tilepal GREEN, GREEN, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY
	tilepal RED, RED, WATER, WATER, GRAY, GRAY, GRAY, GRAY
	tilepal GRAY, GRAY, GRAY, RED, GRAY, GRAY, GRAY, GRAY

TilesetTrainStationPalMap:
	tilepal GRAY, GRAY, GREEN, GREEN, GRAY, GRAY, GRAY, GRAY
	tilepal GRAY, GRAY, GRAY, GRAY, GRAY, GRAY, RED, GRAY
	tilepal GRAY, GRAY, GREEN, GREEN, GRAY, GRAY, GRAY, GRAY
	tilepal GRAY, GRAY, GRAY, GRAY, GRAY, GRAY, RED, GRAY
	tilepal GRAY, GREEN, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY
	tilepal YELLOW, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY
	tilepal WATER, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY
	tilepal GRAY, GRAY, GRAY, GRAY, GRAY, ROOF, GRAY, GRAY
	tilepal YELLOW, YELLOW, YELLOW, YELLOW, WATER, WATER, WATER, WATER
	tilepal BROWN, BROWN, GRAY, GRAY, GREEN, GREEN, WATER, WATER
	tilepal WATER, GREEN, GREEN, WATER, BROWN, BROWN, BROWN, GREEN
	tilepal BROWN, BROWN, GRAY, GRAY, GREEN, GREEN, WATER, WATER

TilesetUndergroundPalMap:
	tilepal GRAY, GRAY, RED, WATER, WATER, WATER, WATER, RED
	tilepal RED, GRAY, WATER, WATER, WATER, WATER, GRAY, GRAY
	tilepal GRAY, RED, RED, WATER, WATER, WATER, WATER, RED
	tilepal RED, GRAY, BROWN, BROWN, BROWN, BROWN, GREEN, GREEN
	tilepal BROWN, BROWN, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY
	tilepal GRAY, GRAY, GRAY, GRAY, GRAY, GRAY, GREEN, GREEN
	tilepal GRAY, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY
	tilepal GRAY, GRAY, GRAY, GRAY, GRAY, GRAY, BROWN, BROWN
	tilepal GRAY, GRAY, GRAY, BROWN, BROWN, YELLOW, YELLOW, GRAY
	tilepal GRAY, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY
	tilepal GRAY, GRAY, GRAY, BROWN, BROWN, YELLOW, YELLOW, GRAY
	tilepal GRAY, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY

TilesetChampionsRoomPalMap:
	tilepal GRAY, GREEN, GREEN, GREEN, RED, GRAY, GRAY, GRAY
	tilepal GRAY, GRAY, RED, RED, GRAY, GRAY, GRAY, GRAY
	tilepal GRAY, GRAY, GREEN, GREEN, RED, GRAY, GRAY, GRAY
	tilepal GRAY, GRAY, RED, RED, GRAY, GRAY, GRAY, GRAY
	tilepal GRAY, GREEN, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY
	tilepal GRAY, GRAY, GRAY, GREEN, GREEN, YELLOW, RED, RED
	tilepal GRAY, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY
	tilepal GRAY, GRAY, GRAY, RED, RED, RED, RED, RED
	tilepal BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN
	tilepal BROWN, GRAY, RED, WATER, WATER, ROOF, GRAY, GRAY
	tilepal BROWN, BROWN, BROWN, BROWN, GRAY, GRAY, BROWN, BROWN
	tilepal GRAY, GRAY, RED, WATER, WATER, ROOF, GRAY, GRAY

TilesetLighthousePalMap:
	tilepal GRAY, WATER, WATER, WATER, BROWN, WATER, WATER, RED
	tilepal RED, RED, RED, BROWN, RED, RED, RED, RED
	tilepal ROOF, WATER, ROOF, BROWN, RED, WATER, WATER, RED
	tilepal RED, RED, RED, WATER, RED, RED, RED, RED
	tilepal ROOF, ROOF, WATER, BROWN, RED, WATER, WATER, GRAY
	tilepal GRAY, GRAY, GRAY, BROWN, RED, ROOF, GRAY, GRAY
	tilepal ROOF, ROOF, WATER, WATER, RED, RED, BROWN, GRAY
	tilepal GRAY, GRAY, GRAY, BROWN, BROWN, ROOF, BROWN, WATER
	tilepal RED, RED, ROOF, ROOF, BROWN, BROWN, GRAY, GRAY
	tilepal RED, RED, GRAY, GRAY, GREEN, GREEN, ROOF, ROOF
	tilepal RED, RED, ROOF, ROOF, ROOF, ROOF, GRAY, GRAY
	tilepal RED, RED, GREEN, GREEN, ROOF, ROOF, GRAY, GRAY

TilesetPlayersRoomPalMap:
	tilepal BROWN, BROWN, BROWN, GRAY, GRAY, GRAY, GRAY, GREEN
	tilepal GREEN, RED, RED, GRAY, GRAY, RED, RED, RED
	tilepal BROWN, BROWN, BROWN, GRAY, GRAY, GRAY, GRAY, GREEN
	tilepal GREEN, RED, RED, GRAY, GRAY, WATER, RED, RED
	tilepal BROWN, BROWN, BROWN, GRAY, GRAY, GRAY, GRAY, GREEN
	tilepal GREEN, ROOF, ROOF, GRAY, GRAY, YELLOW, RED, RED
	tilepal BROWN, BROWN, BROWN, GRAY, GRAY, GRAY, GRAY, GREEN
	tilepal GREEN, ROOF, ROOF, WATER, WATER, GREEN, RED, RED
	tilepal GRAY, GRAY, GRAY, GRAY, BROWN, BROWN, BROWN, GREEN
	tilepal GREEN, YELLOW, YELLOW, WATER, WATER, BROWN, YELLOW, YELLOW
	tilepal GRAY, GRAY, GRAY, GRAY, BROWN, BROWN, BROWN, GREEN
	tilepal GREEN, YELLOW, YELLOW, GRAY, GRAY, BROWN, YELLOW, YELLOW

UnusedMuseumPalMap:
	tilepal WATER, RED, YELLOW, YELLOW, RED, GREEN, GREEN, BROWN
	tilepal BROWN, BROWN, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY
	tilepal GRAY, GRAY, YELLOW, YELLOW, RED, GREEN, GREEN, BROWN
	tilepal BROWN, ROOF, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY
	tilepal GRAY, GRAY, BROWN, BROWN, GRAY, BROWN, BROWN, ROOF
	tilepal ROOF, BROWN, BROWN, BROWN, ROOF, ROOF, ROOF, ROOF
	tilepal ROOF, ROOF, BROWN, BROWN, GRAY, BROWN, BROWN, ROOF
	tilepal ROOF, GRAY, ROOF, BROWN, ROOF, ROOF, GRAY, GRAY
	tilepal GRAY, GRAY, GRAY, GRAY, GRAY, GRAY, ROOF, ROOF
	tilepal GRAY, GRAY, GRAY, GRAY, GRAY, GRAY, RED, RED
	tilepal GRAY, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY
	tilepal GRAY, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY

TilesetIcePathPalMap:
	tilepal BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN
	tilepal GRAY, BROWN, BROWN, BROWN, BROWN, BROWN, WATER, WATER
	tilepal BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN
	tilepal GRAY, BROWN, BROWN, BROWN, BROWN, BROWN, WATER, WATER
	tilepal WATER, BROWN, BROWN, BROWN, BROWN, BROWN, GRAY, GRAY
	tilepal WATER, WATER, BROWN, BROWN, WATER, WATER, WATER, WATER
	tilepal BROWN, WATER, WATER, WATER, WATER, WATER, GRAY, GRAY
	tilepal WATER, WATER, BROWN, BROWN, GRAY, GRAY, WATER, WATER
	tilepal YELLOW, YELLOW, YELLOW, YELLOW, GREEN, GRAY, GRAY, WATER
	tilepal WATER, WATER, WATER, WATER, WATER, WATER, WATER, WATER
	tilepal BROWN, BROWN, GRAY, GRAY, WATER, WATER, WATER, WATER
	tilepal WATER, WATER, WATER, WATER, WATER, WATER, WATER, WATER

TilesetForestPalMap:
	tilepal GRAY, BROWN, BROWN, RED, YELLOW, GREEN, BROWN, YELLOW
	tilepal YELLOW, BROWN, BROWN, BROWN, GREEN, GREEN, GREEN, GREEN
	tilepal BROWN, BROWN, BROWN, RED, WATER, BROWN, BROWN, BROWN
	tilepal BROWN, BROWN, BROWN, BROWN, GREEN, GREEN, GREEN, GREEN
	tilepal BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, GREEN, GREEN
	tilepal GREEN, BROWN, BROWN, BROWN, GREEN, GREEN, GREEN, GREEN
	tilepal BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, GREEN, GREEN
	tilepal GREEN, GREEN, GREEN, BROWN, GREEN, BROWN, BROWN, GREEN
	tilepal BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN
	tilepal BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN
	tilepal BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN
	tilepal BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN
