Music:
	dba Music_None                         
	dba Music_Title                        
	dba Music_Route1                      
	dba Music_Route3                      
	dba Music_Route12                     
	dba Music_MagnetTrain                 
	dba Music_KantoGymLeaderBattle      
	dba Music_KantoTrainerBattle         
	dba Music_KantoWildBattle            
	dba Music_PokemonCenter               
	dba Music_HikerEncounter              
	dba Music_LassEncounter               
	dba Music_OfficerEncounter            
	dba Music_Heal                         
	dba Music_LavenderTown                
	dba Music_Route2                      
	dba Music_MtMoon                      
	dba Music_ShowMeAround               
	dba Music_GameCorner                  
	dba Music_Bicycle                      
	dba Music_HallOfFame                 
	dba Music_ViridianCity                
	dba Music_CeladonCity                 
	dba Music_TrainerVictory              
	dba Music_WildVictory                 
	dba Music_GymVictory                  
	dba Music_MtMoonSquare               
	dba Music_Gym                          
	dba Music_PalletTown                  
	dba Music_PokemonTalk                 
	dba Music_ProfOak                     
	dba Music_RivalEncounter              
	dba Music_RivalAfter                  
	dba Music_Surf                         
	dba Music_Evolution                    
	dba Music_NationalPark                
	dba Music_Credits                      
	dba Music_AzaleaTown                  
	dba Music_CherrygroveCity             
	dba Music_KimonoEncounter             
	dba Music_UnionCave                   
	dba Music_JohtoWildBattle            
	dba Music_JohtoTrainerBattle         
	dba Music_Route30                     
	dba Music_EcruteakCity                
	dba Music_VioletCity                  
	dba Music_JohtoGymLeaderBattle      
	dba Music_ChampionBattle              
	dba Music_RivalBattle                 
	dba Music_RocketBattle                
	dba Music_ProfElm                     
	dba Music_DarkCave                    
	dba Music_Route29                     
	dba Music_Route36                     
	dba Music_SsAqua                      
	dba Music_YoungsterEncounter          
	dba Music_BeautyEncounter             
	dba Music_RocketEncounter             
	dba Music_PokemaniacEncounter         
	dba Music_SageEncounter               
	dba Music_NewBarkTown                
	dba Music_GoldenrodCity               
	dba Music_VermilionCity               
	dba Music_PokemonChannel              
	dba Music_PokeFluteChannel           
	dba Music_TinTower                    
	dba Music_SproutTower                 
	dba Music_BurnedTower                 
	dba Music_Lighthouse                   
	dba Music_LakeOfRage                 
	dba Music_IndigoPlateau               
	dba Music_Route37                     
	dba Music_RocketHideout               
	dba Music_DragonsDen                  
	dba Music_JohtoWildBattleNight      
	dba Music_RuinsOfAlphRadio          
	dba Music_Capture                      
	dba Music_Route26                     
	dba Music_Mom                          
	dba Music_VictoryRoad                 
	dba Music_PokemonLullaby              
	dba Music_PokemonMarch                
	dba Music_GsOpening                   
	dba Music_GsOpening2                 
	dba Music_MainMenu                    
	dba Music_RuinsOfAlphInterior       
	dba Music_RocketOverture              
	dba Music_DancingHall                 
	dba Music_BugCatchingContestRanking 
	dba Music_BugCatchingContest         
	dba Music_LakeOfRageRocketRadio    
	dba Music_Printer                      
	dba Music_PostCredits                 
