; These are all the asm constants needed to make the silver_vc patch.

; [FPA 001 Begin]
EXPORT DEF F_CHAR EQU "F"
EXPORT DEF I_CHAR EQU "I"
EXPORT DEF S_CHAR EQU "S"
EXPORT DEF U_CHAR EQU "U"
EXPORT DEF R_CHAR EQU "R"

; [FPA 002 Begin]
EXPORT DEF E_CHAR EQU "E"
EXPORT DEF L_CHAR EQU "L"
EXPORT DEF D_CHAR EQU "D"

; [FPA 003 Begin]
EXPORT DEF T_CHAR EQU "T"
EXPORT DEF H_CHAR EQU "H"
EXPORT DEF N_CHAR EQU "N"

; [FPA 004 Begin]
EXPORT DEF Y_CHAR EQU "Y"
EXPORT DEF P_CHAR EQU "P"
EXPORT DEF SPACE_CHAR EQU " "

; [FPA 005 Begin]
EXPORT DEF O_CHAR EQU "O"

; [FPA 006 Begin]
EXPORT DEF X_CHAR EQU "X"

; [FPA 007 Begin]
EXPORT DEF A_CHAR EQU "A"
EXPORT DEF AT_CHAR EQU "@"

; [FPA 042801 Begin]
EXPORT BATTLE_ANIM_GFX_BUBBLE

; [fight begin]
EXPORT SCREEN_HEIGHT_PX

; [print forbid 2]
EXPORT NO_INPUT
EXPORT PAD_A
EXPORT PAD_B
EXPORT PAD_UP
EXPORT PAD_DOWN

; [print forbid 3]
EXPORT MAPGROUP_CIANWOOD
EXPORT MAP_CIANWOOD_PHOTO_STUDIO
