MapTriggers:: ; 94000
	dr $94000, $940ed

MapGroupPointers::
	dw MapGroup1
	dw MapGroup2
	dw MapGroup3
	dw MapGroup4
	dw MapGroup5
	dw MapGroup6
	dw MapGroup7
	dw MapGroup8
	dw MapGroup9
	dw MapGroup10
	dw MapGroup11
	dw MapGroup12
	dw MapGroup13
	dw MapGroup14
	dw MapGroup15
	dw MapGroup16
	dw MapGroup17
	dw MapGroup18
	dw MapGroup19
	dw MapGroup20
	dw MapGroup21
	dw MapGroup22
	dw MapGroup23
	dw MapGroup24
	dw MapGroup25
	dw MapGroup26


MapGroup1:
	map_header OlivinePokeCenter1F, TILESET_POKECENTER, INDOOR, OLIVINE_CITY, MUSIC_POKEMON_CENTER, 0, PALETTE_DAY, FISHGROUP_SHORE
	map_header_todo $25, $5b79, TILESET_OLIVINE_GYM, INDOOR, OLIVINE_CITY, MUSIC_GYM, 1, PALETTE_DAY, FISHGROUP_SHORE
	map_header_todo $25, $5b85, TILESET_HOUSE_1, INDOOR, OLIVINE_CITY, MUSIC_VIOLET_CITY, 0, PALETTE_DAY, FISHGROUP_SHORE
	map_header_todo $25, $5b91, TILESET_HOUSE_1, INDOOR, OLIVINE_CITY, MUSIC_VIOLET_CITY, 0, PALETTE_DAY, FISHGROUP_SHORE
	map_header_todo $25, $5b9d, TILESET_HOUSE_1, INDOOR, OLIVINE_CITY, MUSIC_VIOLET_CITY, 0, PALETTE_DAY, FISHGROUP_SHORE
	map_header_todo $25, $5ba9, TILESET_HOUSE_1, INDOOR, OLIVINE_CITY, MUSIC_VIOLET_CITY, 0, PALETTE_DAY, FISHGROUP_SHORE
	map_header_todo $25, $5bb5, TILESET_GAME_CORNER, INDOOR, OLIVINE_CITY, MUSIC_VIOLET_CITY, 0, PALETTE_DAY, FISHGROUP_SHORE
	map_header_todo $25, $5bc1, TILESET_MART, INDOOR, OLIVINE_CITY, MUSIC_VIOLET_CITY, 0, PALETTE_DAY, FISHGROUP_SHORE
	map_header_todo $25, $5bcd, TILESET_GATE, GATE, ROUTE_38, MUSIC_ROUTE_37, 0, PALETTE_DAY, FISHGROUP_SHORE
	map_header_todo $25, $5bd9, TILESET_KURT_HOUSE, INDOOR, ROUTE_39, MUSIC_ECRUTEAK_CITY, 0, PALETTE_DAY, FISHGROUP_SHORE
	map_header_todo $25, $5be5, TILESET_HOUSE_1, INDOOR, ROUTE_39, MUSIC_ECRUTEAK_CITY, 0, PALETTE_DAY, FISHGROUP_SHORE
	map_header_todo $25, $5171, TILESET_JOHTO_1, ROUTE, ROUTE_38, MUSIC_ROUTE_37, 0, PALETTE_AUTO, FISHGROUP_SHORE
	map_header_todo $25, $5195, TILESET_JOHTO_1, ROUTE, ROUTE_39, MUSIC_ROUTE_37, 0, PALETTE_AUTO, FISHGROUP_SHORE
	map_header_todo $25, $4ee9, TILESET_JOHTO_1, TOWN, OLIVINE_CITY, MUSIC_VIOLET_CITY, 0, PALETTE_AUTO, FISHGROUP_SHORE


MapGroup2:
	map_header_todo $25, $5bf1, TILESET_HOUSE_1, INDOOR, MT_MORTAR, MUSIC_CHERRYGROVE_CITY, 0, PALETTE_DAY, FISHGROUP_SHORE
	map_header_todo $25, $5bfd, TILESET_GYM_1, INDOOR, MT_MORTAR, MUSIC_GYM, 1, PALETTE_DAY, FISHGROUP_SHORE
	map_header_todo $25, $5c09, TILESET_POKECENTER, INDOOR, MT_MORTAR, MUSIC_POKEMON_CENTER, 0, PALETTE_DAY, FISHGROUP_SHORE
	map_header_todo $25, $5c15, TILESET_GATE, GATE, CIANWOOD_CITY, MUSIC_LAKE_OF_RAGE, 0, PALETTE_DAY, FISHGROUP_SHORE
	map_header_todo $25, $5201, TILESET_JOHTO_1, ROUTE, CIANWOOD_CITY, MUSIC_LAKE_OF_RAGE, 0, PALETTE_AUTO, FISHGROUP_LAKE
	map_header_todo $25, $5249, TILESET_JOHTO_1, ROUTE, LAKE_OF_RAGE, MUSIC_LAKE_OF_RAGE, 0, PALETTE_AUTO, FISHGROUP_REMORAID
	map_header_todo $25, $4f3d, TILESET_JOHTO_1, TOWN, MT_MORTAR, MUSIC_CHERRYGROVE_CITY, 0, PALETTE_AUTO, FISHGROUP_SHORE


MapGroup3:
	map_header_todo $25, $57f5, TILESET_SPROUT_TOWER, DUNGEON, SPROUT_TOWER, MUSIC_SPROUT_TOWER, 0, PALETTE_DAY, FISHGROUP_SHORE
	map_header_todo $25, $5801, TILESET_SPROUT_TOWER, DUNGEON, SPROUT_TOWER, MUSIC_SPROUT_TOWER, 0, PALETTE_DAY, FISHGROUP_SHORE
	map_header_todo $25, $580d, TILESET_SPROUT_TOWER, DUNGEON, SPROUT_TOWER, MUSIC_SPROUT_TOWER, 0, PALETTE_DAY, FISHGROUP_SHORE
	map_header_todo $25, $5819, TILESET_SPROUT_TOWER, DUNGEON, TIN_TOWER, MUSIC_TIN_TOWER, 0, PALETTE_DAY, FISHGROUP_SHORE
	map_header_todo $25, $5825, TILESET_SPROUT_TOWER, DUNGEON, TIN_TOWER, MUSIC_TIN_TOWER, 0, PALETTE_DAY, FISHGROUP_SHORE
	map_header_todo $25, $5831, TILESET_SPROUT_TOWER, DUNGEON, TIN_TOWER, MUSIC_TIN_TOWER, 0, PALETTE_DAY, FISHGROUP_SHORE
	map_header_todo $25, $583d, TILESET_SPROUT_TOWER, DUNGEON, TIN_TOWER, MUSIC_TIN_TOWER, 0, PALETTE_DAY, FISHGROUP_SHORE
	map_header_todo $25, $5849, TILESET_SPROUT_TOWER, DUNGEON, TIN_TOWER, MUSIC_TIN_TOWER, 0, PALETTE_DAY, FISHGROUP_SHORE
	map_header_todo $25, $5855, TILESET_SPROUT_TOWER, DUNGEON, TIN_TOWER, MUSIC_TIN_TOWER, 0, PALETTE_DAY, FISHGROUP_SHORE
	map_header_todo $25, $5861, TILESET_SPROUT_TOWER, DUNGEON, TIN_TOWER, MUSIC_TIN_TOWER, 0, PALETTE_DAY, FISHGROUP_SHORE
	map_header_todo $25, $586d, TILESET_SPROUT_TOWER, DUNGEON, TIN_TOWER, MUSIC_TIN_TOWER, 0, PALETTE_DAY, FISHGROUP_SHORE
	map_header_todo $25, $5879, TILESET_SPROUT_TOWER, DUNGEON, TIN_TOWER, MUSIC_TIN_TOWER, 0, PALETTE_DAY, FISHGROUP_SHORE
	map_header_todo $25, $5885, TILESET_SPROUT_TOWER, DUNGEON, BURNED_TOWER, MUSIC_BURNED_TOWER, 0, PALETTE_DAY, FISHGROUP_SHORE
	map_header_todo $25, $5891, TILESET_CAVE, CAVE, BURNED_TOWER, MUSIC_BURNED_TOWER, 1, PALETTE_DAY, FISHGROUP_SHORE
	map_header_todo $25, $589d, TILESET_PARK, ROUTE, NATIONAL_PARK, MUSIC_NATIONAL_PARK, 0, PALETTE_AUTO, FISHGROUP_SHORE
	map_header_todo $25, $58a9, TILESET_PARK, ROUTE, NATIONAL_PARK, MUSIC_BUG_CATCHING_CONTEST, 0, PALETTE_AUTO, FISHGROUP_SHORE
	map_header_todo $25, $58b5, TILESET_RADIO_TOWER, INDOOR, RADIO_TOWER, $bd, 1, PALETTE_DAY, FISHGROUP_SHORE
	map_header_todo $25, $58c1, TILESET_RADIO_TOWER, INDOOR, RADIO_TOWER, $bd, 1, PALETTE_DAY, FISHGROUP_SHORE
	map_header_todo $25, $58cd, TILESET_RADIO_TOWER, INDOOR, RADIO_TOWER, $bd, 1, PALETTE_DAY, FISHGROUP_SHORE
	map_header_todo $25, $58d9, TILESET_RADIO_TOWER, INDOOR, RADIO_TOWER, $bd, 1, PALETTE_DAY, FISHGROUP_SHORE
	map_header_todo $25, $58e5, TILESET_RADIO_TOWER, INDOOR, RADIO_TOWER, $bd, 1, PALETTE_DAY, FISHGROUP_SHORE
	map_header_todo $25, $58f1, TILESET_JOHTO_1, ROUTE, RUINS_OF_ALPH, MUSIC_UNION_CAVE, 0, PALETTE_AUTO, FISHGROUP_POND
	map_header_todo $25, $58fd, TILESET_RUINS_OF_ALPH, DUNGEON, RUINS_OF_ALPH, MUSIC_UNION_CAVE, 1, PALETTE_DAY, FISHGROUP_SHORE
	map_header_todo $25, $5909, TILESET_RUINS_OF_ALPH, DUNGEON, RUINS_OF_ALPH, MUSIC_UNION_CAVE, 1, PALETTE_DAY, FISHGROUP_SHORE
	map_header_todo $25, $5915, TILESET_RUINS_OF_ALPH, DUNGEON, RUINS_OF_ALPH, MUSIC_UNION_CAVE, 1, PALETTE_DAY, FISHGROUP_SHORE
	map_header_todo $25, $5921, TILESET_RUINS_OF_ALPH, DUNGEON, RUINS_OF_ALPH, MUSIC_UNION_CAVE, 1, PALETTE_DAY, FISHGROUP_SHORE
	map_header_todo $25, $592d, TILESET_RUINS_OF_ALPH, DUNGEON, RUINS_OF_ALPH, MUSIC_RUINS_OF_ALPH_INTERIOR, 1, PALETTE_DAY, FISHGROUP_SHORE
	map_header_todo $25, $5939, TILESET_POWER_PLANT, INDOOR, RUINS_OF_ALPH, MUSIC_UNION_CAVE, 0, PALETTE_DAY, FISHGROUP_SHORE
	map_header_todo $25, $5945, TILESET_CAVE, CAVE, UNION_CAVE, MUSIC_UNION_CAVE, 1, PALETTE_NITE, FISHGROUP_LAKE
	map_header_todo $25, $5951, TILESET_CAVE, CAVE, UNION_CAVE, MUSIC_UNION_CAVE, 1, PALETTE_NITE, FISHGROUP_LAKE
	map_header_todo $25, $595d, TILESET_CAVE, CAVE, UNION_CAVE, MUSIC_UNION_CAVE, 1, PALETTE_NITE, FISHGROUP_SHORE
	map_header_todo $25, $5969, TILESET_CAVE, CAVE, SLOWPOKE_WELL, MUSIC_DARK_CAVE, 1, PALETTE_NITE, FISHGROUP_LAKE
	map_header_todo $25, $5975, TILESET_CAVE, CAVE, SLOWPOKE_WELL, MUSIC_DARK_CAVE, 1, PALETTE_NITE, FISHGROUP_LAKE
	map_header_todo $25, $5981, TILESET_LIGHTHOUSE, DUNGEON, LIGHTHOUSE, MUSIC_LIGHTHOUSE, 0, PALETTE_DAY, FISHGROUP_SHORE
	map_header_todo $25, $598d, TILESET_LIGHTHOUSE, DUNGEON, LIGHTHOUSE, MUSIC_LIGHTHOUSE, 0, PALETTE_DAY, FISHGROUP_SHORE
	map_header_todo $25, $5999, TILESET_LIGHTHOUSE, DUNGEON, LIGHTHOUSE, MUSIC_LIGHTHOUSE, 0, PALETTE_DAY, FISHGROUP_SHORE
	map_header_todo $25, $59a5, TILESET_LIGHTHOUSE, DUNGEON, LIGHTHOUSE, MUSIC_LIGHTHOUSE, 0, PALETTE_DAY, FISHGROUP_SHORE
	map_header_todo $25, $59b1, TILESET_LIGHTHOUSE, DUNGEON, LIGHTHOUSE, MUSIC_LIGHTHOUSE, 0, PALETTE_DAY, FISHGROUP_SHORE
	map_header_todo $25, $59bd, TILESET_LIGHTHOUSE, DUNGEON, LIGHTHOUSE, MUSIC_VIOLET_CITY, 0, PALETTE_DAY, FISHGROUP_SHORE
	map_header_todo $25, $59c9, TILESET_KURT_HOUSE, INDOOR, MT_MORTAR, MUSIC_MAHOGANY_MART, 1, PALETTE_DAY, FISHGROUP_SHORE
	map_header_todo $25, $59d5, TILESET_UNDERGROUND, DUNGEON, MT_MORTAR, MUSIC_ROCKET_HIDEOUT, 1, PALETTE_DAY, FISHGROUP_SHORE
	map_header_todo $25, $59e1, TILESET_POWER_PLANT, DUNGEON, MT_MORTAR, MUSIC_ROCKET_HIDEOUT, 1, PALETTE_DAY, FISHGROUP_SHORE
	map_header_todo $25, $59ed, TILESET_POWER_PLANT, DUNGEON, MT_MORTAR, MUSIC_ROCKET_HIDEOUT, 1, PALETTE_DAY, FISHGROUP_SHORE
	map_header_todo $25, $59f9, TILESET_ILEX_FOREST, CAVE, ILEX_FOREST, MUSIC_UNION_CAVE, 0, PALETTE_NITE, FISHGROUP_POND
	map_header_todo $25, $5a05, TILESET_GATE, DUNGEON, GOLDENROD_CITY, MUSIC_UNION_CAVE, 1, PALETTE_DAY, FISHGROUP_SHORE
	map_header_todo $25, $5a11, TILESET_GYM_1, DUNGEON, GOLDENROD_CITY, MUSIC_UNION_CAVE, 1, PALETTE_DAY, FISHGROUP_SHORE
	map_header_todo $25, $5a1d, TILESET_UNDERGROUND, DUNGEON, GOLDENROD_CITY, MUSIC_GOLDENROD_CITY, 1, PALETTE_DAY, FISHGROUP_SHORE
	map_header_todo $25, $5a29, TILESET_UNDERGROUND, DUNGEON, GOLDENROD_CITY, MUSIC_UNION_CAVE, 1, PALETTE_DAY, FISHGROUP_SHORE
	map_header_todo $25, $5a35, TILESET_WHIRL_ISLANDS, CAVE, ROUTE_42, MUSIC_UNION_CAVE, 1, PALETTE_DARK, FISHGROUP_LAKE
	map_header_todo $25, $5a41, TILESET_WHIRL_ISLANDS, CAVE, ROUTE_42, MUSIC_UNION_CAVE, 1, PALETTE_DARK, FISHGROUP_LAKE
	map_header_todo $25, $5a4d, TILESET_WHIRL_ISLANDS, CAVE, ROUTE_42, MUSIC_UNION_CAVE, 1, PALETTE_DARK, FISHGROUP_LAKE
	map_header_todo $25, $5a59, TILESET_WHIRL_ISLANDS, CAVE, ROUTE_42, MUSIC_UNION_CAVE, 1, PALETTE_DARK, FISHGROUP_LAKE
	map_header_todo $25, $5a65, TILESET_ICE_PATH, CAVE, ROUTE_44, MUSIC_DARK_CAVE, 1, PALETTE_NITE, FISHGROUP_DRATINI
	map_header_todo $25, $5a71, TILESET_ICE_PATH, CAVE, ROUTE_44, MUSIC_DARK_CAVE, 1, PALETTE_NITE, FISHGROUP_DRATINI
	map_header_todo $25, $5a7d, TILESET_ICE_PATH, CAVE, ROUTE_44, MUSIC_DARK_CAVE, 1, PALETTE_NITE, FISHGROUP_DRATINI
	map_header_todo $25, $5a89, TILESET_ICE_PATH, CAVE, ROUTE_44, MUSIC_DARK_CAVE, 1, PALETTE_NITE, FISHGROUP_DRATINI
	map_header_todo $25, $5a95, TILESET_ICE_PATH, CAVE, ROUTE_44, MUSIC_DARK_CAVE, 1, PALETTE_NITE, FISHGROUP_DRATINI
	map_header_todo $25, $5aa1, TILESET_WHIRL_ISLANDS, CAVE, ROUTE_40, MUSIC_UNION_CAVE, 1, PALETTE_DARK, FISHGROUP_WHIRL_ISLANDS
	map_header_todo $25, $5aad, TILESET_WHIRL_ISLANDS, CAVE, ROUTE_40, MUSIC_UNION_CAVE, 1, PALETTE_DARK, FISHGROUP_WHIRL_ISLANDS
	map_header_todo $25, $5ab9, TILESET_WHIRL_ISLANDS, CAVE, ROUTE_40, MUSIC_UNION_CAVE, 1, PALETTE_DARK, FISHGROUP_WHIRL_ISLANDS
	map_header_todo $25, $5ac5, TILESET_WHIRL_ISLANDS, CAVE, ROUTE_40, MUSIC_UNION_CAVE, 1, PALETTE_DARK, FISHGROUP_WHIRL_ISLANDS
	map_header_todo $25, $5ad1, TILESET_WHIRL_ISLANDS, CAVE, ROUTE_40, MUSIC_UNION_CAVE, 1, PALETTE_DARK, FISHGROUP_WHIRL_ISLANDS
	map_header_todo $25, $5add, TILESET_WHIRL_ISLANDS, CAVE, ROUTE_40, MUSIC_UNION_CAVE, 1, PALETTE_DARK, FISHGROUP_WHIRL_ISLANDS
	map_header_todo $25, $5ae9, TILESET_WHIRL_ISLANDS, CAVE, ROUTE_40, MUSIC_UNION_CAVE, 1, PALETTE_DARK, FISHGROUP_WHIRL_ISLANDS
	map_header_todo $25, $5af5, TILESET_WHIRL_ISLANDS, CAVE, ROUTE_40, MUSIC_UNION_CAVE, 1, PALETTE_DARK, FISHGROUP_WHIRL_ISLANDS
	map_header_todo $25, $5b01, TILESET_WHIRL_ISLANDS, CAVE, ROUTE_46, MUSIC_LIGHTHOUSE, 1, PALETTE_DARK, FISHGROUP_LAKE
	map_header_todo $25, $5b0d, TILESET_CAVE, CAVE, ROUTE_46, MUSIC_LIGHTHOUSE, 1, PALETTE_NITE, FISHGROUP_LAKE
	map_header_todo $25, $5b19, TILESET_CAVE, CAVE, ROUTE_46, MUSIC_LIGHTHOUSE, 1, PALETTE_DAY, FISHGROUP_LAKE
	map_header_todo $25, $5b25, TILESET_CAVE, CAVE, ROUTE_46, MUSIC_LIGHTHOUSE, 1, PALETTE_NITE, FISHGROUP_LAKE
	map_header_todo $25, $5b31, TILESET_WHIRL_ISLANDS, CAVE, ROUTE_45, MUSIC_DARK_CAVE, 1, PALETTE_DARK, FISHGROUP_LAKE
	map_header_todo $25, $5b3d, TILESET_WHIRL_ISLANDS, CAVE, ROUTE_45, MUSIC_DARK_CAVE, 1, PALETTE_DARK, FISHGROUP_LAKE
	map_header_todo $25, $5b49, TILESET_CAVE, CAVE, BLACKTHORN_CITY, MUSIC_DRAGONS_DEN, 1, PALETTE_NITE, FISHGROUP_DRATINI
	map_header_todo $25, $5b55, TILESET_JOHTO_1, CAVE, BLACKTHORN_CITY, MUSIC_DRAGONS_DEN, 1, PALETTE_NITE, FISHGROUP_DRATINI
	map_header_todo $25, $5b61, TILESET_CAVE, CAVE, ROUTE_27, MUSIC_UNION_CAVE, 1, PALETTE_NITE, FISHGROUP_LAKE
	map_header_todo $25, $5c21, TILESET_CAVE, CAVE, VERMILION_CITY, MUSIC_MT_MOON, 1, PALETTE_NITE, FISHGROUP_SHORE
	map_header_todo $25, $5c2d, TILESET_CAVE, CAVE, ROUTE_3, MUSIC_MT_MOON, 1, PALETTE_NITE, FISHGROUP_SHORE
	map_header_todo $25, $5c39, TILESET_UNDERGROUND, GATE, ROUTE_5, MUSIC_MT_MOON, 0, PALETTE_NITE, FISHGROUP_SHORE
	map_header_todo $25, $5c45, TILESET_WHIRL_ISLANDS, CAVE, ROUTE_9, MUSIC_MT_MOON, 1, PALETTE_DARK, FISHGROUP_SHORE
	map_header_todo $25, $5c51, TILESET_WHIRL_ISLANDS, CAVE, ROUTE_9, MUSIC_MT_MOON, 1, PALETTE_DARK, FISHGROUP_SHORE
	map_header_todo $25, $5c5d, TILESET_GATE, INDOOR, ROUTE_18, MUSIC_VIRIDIAN_CITY, 0, PALETTE_DAY, FISHGROUP_SHORE
	map_header_todo $25, $5c69, TILESET_PARK, CAVE, ROUTE_18, MUSIC_EVOLUTION, 0, PALETTE_AUTO, FISHGROUP_SHORE
	map_header_todo $25, $5c75, TILESET_CAVE, CAVE, ROUTE_22, MUSIC_VICTORY_ROAD, 1, PALETTE_NITE, FISHGROUP_SHORE


MapGroup4:
	map_header_todo $25, $5c81, TILESET_SPROUT_TOWER, INDOOR, ECRUTEAK_CITY, MUSIC_ECRUTEAK_CITY, 0, PALETTE_DAY, FISHGROUP_SHORE
	map_header_todo $25, $5c8d, TILESET_KURT_HOUSE, INDOOR, ECRUTEAK_CITY, MUSIC_ECRUTEAK_CITY, 0, PALETTE_DAY, FISHGROUP_SHORE
	map_header_todo $25, $5c99, TILESET_POKECENTER, INDOOR, ECRUTEAK_CITY, MUSIC_POKEMON_CENTER, 0, PALETTE_DAY, FISHGROUP_SHORE
	map_header_todo $25, $5ca5, TILESET_KURT_HOUSE, INDOOR, ECRUTEAK_CITY, MUSIC_ECRUTEAK_CITY, 0, PALETTE_DAY, FISHGROUP_SHORE
	map_header_todo $25, $5cb1, TILESET_KURT_HOUSE, INDOOR, ECRUTEAK_CITY, MUSIC_DANCING_HALL, 0, PALETTE_DAY, FISHGROUP_SHORE
	map_header_todo $25, $5cbd, TILESET_MART, INDOOR, ECRUTEAK_CITY, MUSIC_ECRUTEAK_CITY, 0, PALETTE_DAY, FISHGROUP_SHORE
	map_header_todo $25, $5cc9, TILESET_SPROUT_TOWER, INDOOR, ECRUTEAK_CITY, MUSIC_GYM, 1, PALETTE_DAY, FISHGROUP_SHORE
	map_header_todo $25, $5cd5, TILESET_KURT_HOUSE, INDOOR, ECRUTEAK_CITY, MUSIC_ECRUTEAK_CITY, 0, PALETTE_DAY, FISHGROUP_SHORE
	map_header_todo $25, $4f0d, TILESET_JOHTO_1, TOWN, ECRUTEAK_CITY, MUSIC_ECRUTEAK_CITY, 0, PALETTE_AUTO, FISHGROUP_POND


MapGroup5:
	map_header_todo $25, $5ce1, TILESET_GYM_1, INDOOR, ICE_PATH, MUSIC_GYM, 1, PALETTE_DAY, FISHGROUP_SHORE
	map_header_todo $25, $5ced, TILESET_GYM_1, INDOOR, ICE_PATH, MUSIC_GYM, 1, PALETTE_DAY, FISHGROUP_SHORE
	map_header_todo $25, $5cf9, TILESET_HOUSE_1, INDOOR, ICE_PATH, MUSIC_AZALEA_TOWN, 0, PALETTE_DAY, FISHGROUP_SHORE
	map_header_todo $25, $5d05, TILESET_HOUSE_1, INDOOR, ICE_PATH, MUSIC_AZALEA_TOWN, 0, PALETTE_DAY, FISHGROUP_SHORE
	map_header_todo $25, $5d11, TILESET_MART, INDOOR, ICE_PATH, MUSIC_AZALEA_TOWN, 0, PALETTE_DAY, FISHGROUP_SHORE
	map_header_todo $25, $5d1d, TILESET_POKECENTER, INDOOR, ICE_PATH, MUSIC_POKEMON_CENTER, 0, PALETTE_DAY, FISHGROUP_SHORE
	map_header_todo $25, $5d29, TILESET_HOUSE_1, INDOOR, ICE_PATH, MUSIC_AZALEA_TOWN, 0, PALETTE_DAY, FISHGROUP_SHORE
	map_header_todo $25, $526d, TILESET_JOHTO_1, ROUTE, DRAGONS_DEN, MUSIC_ROUTE_36, 0, PALETTE_AUTO, FISHGROUP_DRATINI_2
	map_header_todo $25, $5291, TILESET_JOHTO_1, ROUTE, DARK_CAVE, MUSIC_ROUTE_36, 0, PALETTE_AUTO, FISHGROUP_SHORE
	map_header_todo $25, $4f85, TILESET_JOHTO_1, TOWN, ICE_PATH, MUSIC_AZALEA_TOWN, 0, PALETTE_AUTO, FISHGROUP_POND


MapGroup6:
	map_header_todo $25, $5d35, TILESET_POKECENTER, INDOOR, SEAFOAM_ISLANDS, MUSIC_POKEMON_CENTER, 0, PALETTE_DAY, FISHGROUP_SHORE
	map_header_todo $25, $5d41, TILESET_POKECENTER, INDOOR, SEAFOAM_ISLANDS, MUSIC_POKEMON_CENTER, 0, PALETTE_DAY, FISHGROUP_SHORE
	map_header_todo $25, $5d4d, TILESET_GATE, GATE, FUCHSIA_CITY, MUSIC_ROUTE_3, 0, PALETTE_DAY, FISHGROUP_SHORE
	map_header_todo $25, $5d59, TILESET_CAVE, INDOOR, ROUTE_20, MUSIC_GYM, 1, PALETTE_DAY, FISHGROUP_SHORE
	map_header_todo $25, $53f9, TILESET_KANTO, ROUTE, FUCHSIA_CITY, MUSIC_ROUTE_3, 0, PALETTE_AUTO, FISHGROUP_SHORE
	map_header_todo $25, $53d5, TILESET_KANTO, ROUTE, ROUTE_19, MUSIC_ROUTE_3, 0, PALETTE_AUTO, FISHGROUP_OCEAN
	map_header_todo $25, $538d, TILESET_KANTO, ROUTE, CINNABAR_ISLAND, MUSIC_ROUTE_3, 0, PALETTE_AUTO, FISHGROUP_OCEAN
	map_header_todo $25, $53b1, TILESET_KANTO, TOWN, SEAFOAM_ISLANDS, MUSIC_VIRIDIAN_CITY, 0, PALETTE_AUTO, FISHGROUP_OCEAN


MapGroup7:
	map_header_todo $25, $5d65, TILESET_HOUSE_1, INDOOR, ROUTE_4, MUSIC_VIRIDIAN_CITY, 0, PALETTE_DAY, FISHGROUP_SHORE
	map_header_todo $25, $5d71, TILESET_HOUSE_1, INDOOR, ROUTE_4, MUSIC_VIRIDIAN_CITY, 0, PALETTE_DAY, FISHGROUP_SHORE
	map_header_todo $25, $5d7d, TILESET_HOUSE_1, INDOOR, ROUTE_4, MUSIC_VIRIDIAN_CITY, 0, PALETTE_DAY, FISHGROUP_SHORE
	map_header_todo $25, $5d89, TILESET_POKECENTER, INDOOR, ROUTE_4, MUSIC_POKEMON_CENTER, 0, PALETTE_DAY, FISHGROUP_SHORE
	map_header_todo $25, $5d95, TILESET_POKECENTER, INDOOR, ROUTE_4, MUSIC_POKEMON_CENTER, 0, PALETTE_DAY, FISHGROUP_SHORE
	map_header_todo $25, $5da1, TILESET_PORT, INDOOR, ROUTE_4, MUSIC_GYM, 1, PALETTE_DAY, FISHGROUP_SHORE
	map_header_todo $25, $5dad, TILESET_MART, INDOOR, ROUTE_4, MUSIC_VIRIDIAN_CITY, 0, PALETTE_DAY, FISHGROUP_SHORE
	map_header_todo $25, $5db9, TILESET_POKECENTER, INDOOR, ROCK_TUNNEL, MUSIC_POKEMON_CENTER, 0, PALETTE_DAY, FISHGROUP_SHORE
	map_header_todo $25, $5dc5, TILESET_POKECENTER, INDOOR, ROCK_TUNNEL, MUSIC_POKEMON_CENTER, 0, PALETTE_DAY, FISHGROUP_SHORE
	map_header_todo $25, $5dd1, TILESET_POWER_PLANT, INDOOR, ROUTE_10, MUSIC_VIRIDIAN_CITY, 0, PALETTE_DAY, FISHGROUP_SHORE
	map_header_todo $25, $5ddd, TILESET_HOUSE_1, INDOOR, ROUTE_24, MUSIC_VIRIDIAN_CITY, 0, PALETTE_DAY, FISHGROUP_SHORE
	map_header_todo $25, $5759, TILESET_KANTO, ROUTE, MT_MOON, MUSIC_ROUTE_3, 0, PALETTE_AUTO, FISHGROUP_LAKE
	map_header_todo $25, $56d5, TILESET_KANTO, ROUTE, ROUTE_8, MUSIC_ROUTE_3, 0, PALETTE_AUTO, FISHGROUP_LAKE
	map_header_todo $25, $57a1, TILESET_KANTO, ROUTE, ROCK_TUNNEL, MUSIC_ROUTE_3, 0, PALETTE_AUTO, FISHGROUP_LAKE
	map_header_todo $25, $56f9, TILESET_KANTO, ROUTE, CERULEAN_CITY, MUSIC_ROUTE_3, 0, PALETTE_AUTO, FISHGROUP_LAKE
	map_header_todo $25, $571d, TILESET_KANTO, ROUTE, ROUTE_24, MUSIC_ROUTE_3, 0, PALETTE_AUTO, FISHGROUP_LAKE
	map_header_todo $25, $5699, TILESET_KANTO, TOWN, ROUTE_4, MUSIC_VIRIDIAN_CITY, 0, PALETTE_AUTO, FISHGROUP_LAKE


MapGroup8:
	map_header_todo $25, $5de9, TILESET_POKECENTER, INDOOR, AZALEA_TOWN, MUSIC_POKEMON_CENTER, 0, PALETTE_DAY, FISHGROUP_SHORE
	map_header_todo $25, $5df5, TILESET_HOUSE_1, INDOOR, AZALEA_TOWN, MUSIC_AZALEA_TOWN, 0, PALETTE_DAY, FISHGROUP_SHORE
	map_header_todo $25, $5e01, TILESET_MART, INDOOR, AZALEA_TOWN, MUSIC_AZALEA_TOWN, 0, PALETTE_DAY, FISHGROUP_SHORE
	map_header_todo $25, $5e0d, TILESET_KURT_HOUSE, INDOOR, AZALEA_TOWN, MUSIC_AZALEA_TOWN, 0, PALETTE_DAY, FISHGROUP_SHORE
	map_header_todo $25, $5e19, TILESET_GYM_1, INDOOR, AZALEA_TOWN, MUSIC_GYM, 1, PALETTE_DAY, FISHGROUP_SHORE
	map_header_todo $25, $50b1, TILESET_JOHTO_2, ROUTE, ROUTE_33, MUSIC_ROUTE_30, 0, PALETTE_AUTO, FISHGROUP_SHORE
	map_header_todo $25, $4e89, TILESET_JOHTO_2, TOWN, AZALEA_TOWN, MUSIC_AZALEA_TOWN, 0, PALETTE_AUTO, FISHGROUP_SHORE


MapGroup9:
	map_header_todo $25, $5e25, TILESET_HOUSE_1, INDOOR, ROUTE_43, MUSIC_LAKE_OF_RAGE, 0, PALETTE_DAY, FISHGROUP_SHORE
	map_header_todo $25, $5e31, TILESET_HOUSE_1, INDOOR, ROUTE_43, MUSIC_LAKE_OF_RAGE, 0, PALETTE_DAY, FISHGROUP_SHORE
	map_header_todo $25, $5e3d, TILESET_GATE, GATE, MAHOGANY_TOWN, MUSIC_LAKE_OF_RAGE, 0, PALETTE_DAY, FISHGROUP_SHORE
	map_header_todo $25, $5e49, TILESET_GATE, GATE, MAHOGANY_TOWN, MUSIC_LAKE_OF_RAGE, 0, PALETTE_DAY, FISHGROUP_SHORE
	map_header_todo $25, $5225, TILESET_JOHTO_1, ROUTE, MAHOGANY_TOWN, MUSIC_LAKE_OF_RAGE, 0, PALETTE_AUTO, FISHGROUP_POND
	map_header_todo $25, $4f6d, TILESET_JOHTO_1, TOWN, ROUTE_43, MUSIC_LAKE_OF_RAGE, 0, PALETTE_AUTO, FISHGROUP_GYARADOS


MapGroup10:
	map_header_todo $25, $508d, TILESET_JOHTO_1, ROUTE, ROUTE_32, MUSIC_ROUTE_30, 0, PALETTE_AUTO, FISHGROUP_QWILFISH
	map_header_todo $25, $50f9, TILESET_JOHTO_1, ROUTE, ROUTE_35, MUSIC_ROUTE_36, 0, PALETTE_AUTO, FISHGROUP_POND
	map_header_todo $25, $511d, TILESET_JOHTO_1, ROUTE, ROUTE_36, MUSIC_ROUTE_36, 0, PALETTE_AUTO, FISHGROUP_SHORE
	map_header_todo $25, $514d, TILESET_JOHTO_1, ROUTE, ROUTE_37, MUSIC_ROUTE_36, 0, PALETTE_AUTO, FISHGROUP_SHORE
	map_header_todo $25, $4e59, TILESET_JOHTO_1, TOWN, VIOLET_CITY, MUSIC_VIOLET_CITY, 0, PALETTE_AUTO, FISHGROUP_POND
	map_header_todo $25, $5e55, TILESET_MART, INDOOR, VIOLET_CITY, MUSIC_VIOLET_CITY, 0, PALETTE_DAY, FISHGROUP_SHORE
	map_header_todo $25, $5e61, TILESET_GYM_1, INDOOR, VIOLET_CITY, MUSIC_GYM, 1, PALETTE_DAY, FISHGROUP_SHORE
	map_header_todo $25, $5e6d, TILESET_LAB, INDOOR, VIOLET_CITY, MUSIC_VIOLET_CITY, 0, PALETTE_DAY, FISHGROUP_SHORE
	map_header_todo $25, $5e79, TILESET_KURT_HOUSE, INDOOR, VIOLET_CITY, MUSIC_VIOLET_CITY, 0, PALETTE_DAY, FISHGROUP_SHORE
	map_header_todo $25, $5e85, TILESET_POKECENTER, INDOOR, VIOLET_CITY, MUSIC_POKEMON_CENTER, 0, PALETTE_DAY, FISHGROUP_SHORE
	map_header_todo $25, $5e91, TILESET_KURT_HOUSE, INDOOR, VIOLET_CITY, MUSIC_VIOLET_CITY, 0, PALETTE_DAY, FISHGROUP_SHORE
	map_header_todo $25, $5e9d, TILESET_GATE, GATE, ROUTE_32, MUSIC_ROUTE_30, 0, PALETTE_DAY, FISHGROUP_SHORE
	map_header_todo $25, $5ea9, TILESET_POKECENTER, INDOOR, ROUTE_32, MUSIC_POKEMON_CENTER, 0, PALETTE_DAY, FISHGROUP_SHORE
	map_header_todo $25, $5eb5, TILESET_GATE, GATE, ROUTE_35, MUSIC_ROUTE_36, 0, PALETTE_DAY, FISHGROUP_SHORE
	map_header_todo $25, $5ec1, TILESET_GATE, INDOOR, ROUTE_35, MUSIC_GOLDENROD_CITY, 0, PALETTE_DAY, FISHGROUP_SHORE
	map_header_todo $25, $5ecd, TILESET_GATE, GATE, ROUTE_36, MUSIC_ROUTE_36, 0, PALETTE_DAY, FISHGROUP_SHORE
	map_header_todo $25, $5ed9, TILESET_GATE, INDOOR, ROUTE_36, MUSIC_GOLDENROD_CITY, 0, PALETTE_DAY, FISHGROUP_SHORE


MapGroup11:
	map_header_todo $25, $50d5, TILESET_JOHTO_2, ROUTE, ROUTE_34, MUSIC_ROUTE_36, 0, PALETTE_AUTO, FISHGROUP_SHORE
	map_header_todo $25, $4ec5, TILESET_JOHTO_2, TOWN, GOLDENROD_CITY, MUSIC_GOLDENROD_CITY, 0, PALETTE_AUTO, FISHGROUP_SHORE
	map_header_todo $25, $5ee5, TILESET_GYM_1, INDOOR, GOLDENROD_CITY, MUSIC_GYM, 1, PALETTE_DAY, FISHGROUP_SHORE
	map_header_todo $25, $5ef1, TILESET_OLIVINE_GYM, INDOOR, GOLDENROD_CITY, MUSIC_GOLDENROD_CITY, 0, PALETTE_DAY, FISHGROUP_SHORE
	map_header_todo $25, $5efd, TILESET_HOUSE_1, INDOOR, GOLDENROD_CITY, MUSIC_GOLDENROD_CITY, 0, PALETTE_DAY, FISHGROUP_SHORE
	map_header_todo $25, $5f09, TILESET_HOUSE_1, INDOOR, GOLDENROD_CITY, MUSIC_GOLDENROD_CITY, 0, PALETTE_DAY, FISHGROUP_SHORE
	map_header_todo $25, $5f15, TILESET_TRAIN_STATION, INDOOR, GOLDENROD_CITY, MUSIC_GOLDENROD_CITY, 0, PALETTE_DAY, FISHGROUP_SHORE
	map_header_todo $25, $5f21, TILESET_HOUSE_1, INDOOR, GOLDENROD_CITY, MUSIC_GOLDENROD_CITY, 0, PALETTE_DAY, FISHGROUP_SHORE
	map_header_todo $25, $5f2d, TILESET_POKECENTER, INDOOR, GOLDENROD_CITY, MUSIC_POKEMON_CENTER, 0, PALETTE_DAY, FISHGROUP_SHORE
	map_header_todo $25, $5f39, TILESET_HOUSE_1, INDOOR, GOLDENROD_CITY, MUSIC_GOLDENROD_CITY, 0, PALETTE_DAY, FISHGROUP_SHORE
	map_header_todo $25, $5f45, TILESET_HOUSE_1, INDOOR, GOLDENROD_CITY, MUSIC_GOLDENROD_CITY, 0, PALETTE_DAY, FISHGROUP_SHORE
	map_header_todo $25, $5f51, TILESET_MART, INDOOR, GOLDENROD_CITY, MUSIC_GOLDENROD_CITY, 0, PALETTE_DAY, FISHGROUP_SHORE
	map_header_todo $25, $5f5d, TILESET_MART, INDOOR, GOLDENROD_CITY, MUSIC_GOLDENROD_CITY, 0, PALETTE_DAY, FISHGROUP_SHORE
	map_header_todo $25, $5f69, TILESET_MART, INDOOR, GOLDENROD_CITY, MUSIC_GOLDENROD_CITY, 0, PALETTE_DAY, FISHGROUP_SHORE
	map_header_todo $25, $5f75, TILESET_MART, INDOOR, GOLDENROD_CITY, MUSIC_GOLDENROD_CITY, 0, PALETTE_DAY, FISHGROUP_SHORE
	map_header_todo $25, $5f81, TILESET_MART, INDOOR, GOLDENROD_CITY, MUSIC_GOLDENROD_CITY, 0, PALETTE_DAY, FISHGROUP_SHORE
	map_header_todo $25, $5f8d, TILESET_MART, INDOOR, GOLDENROD_CITY, MUSIC_GOLDENROD_CITY, 0, PALETTE_DAY, FISHGROUP_SHORE
	map_header_todo $25, $5f99, TILESET_MART, INDOOR, GOLDENROD_CITY, MUSIC_GOLDENROD_CITY, 0, PALETTE_DAY, FISHGROUP_SHORE
	map_header_todo $25, $5fa5, TILESET_GAME_CORNER, INDOOR, GOLDENROD_CITY, MUSIC_GAME_CORNER, 0, PALETTE_DAY, FISHGROUP_SHORE
	map_header_todo $25, $5fb1, TILESET_GATE, GATE, ROUTE_34, MUSIC_ROUTE_36, 0, PALETTE_DAY, FISHGROUP_SHORE
	map_header_todo $25, $5fbd, TILESET_GATE, GATE, ROUTE_34, MUSIC_ROUTE_36, 0, PALETTE_DAY, FISHGROUP_SHORE
	map_header_todo $25, $5fc9, TILESET_HOUSE_1, INDOOR, ROUTE_34, MUSIC_AZALEA_TOWN, 0, PALETTE_DAY, FISHGROUP_SHORE


MapGroup12:
	map_header_todo $25, $5615, TILESET_KANTO, ROUTE, UNDERGROUND, MUSIC_ROUTE_3, 0, PALETTE_AUTO, FISHGROUP_POND
	map_header_todo $25, $559d, TILESET_KANTO, ROUTE, SAFFRON_CITY, MUSIC_ROUTE_12, 0, PALETTE_AUTO, FISHGROUP_SHORE
	map_header_todo $25, $55f1, TILESET_KANTO, TOWN, ROUTE_6, MUSIC_VERMILION_CITY, 0, PALETTE_AUTO, FISHGROUP_OCEAN
	map_header_todo $25, $5fd5, TILESET_HOUSE_1, INDOOR, ROUTE_6, MUSIC_VERMILION_CITY, 0, PALETTE_DAY, FISHGROUP_SHORE
	map_header_todo $25, $5fe1, TILESET_POKECENTER, INDOOR, ROUTE_6, MUSIC_POKEMON_CENTER, 0, PALETTE_DAY, FISHGROUP_SHORE
	map_header_todo $25, $5fed, TILESET_POKECENTER, INDOOR, ROUTE_6, MUSIC_VERMILION_CITY, 0, PALETTE_DAY, FISHGROUP_SHORE
	map_header_todo $25, $5ff9, TILESET_HOUSE_1, INDOOR, ROUTE_6, MUSIC_VERMILION_CITY, 0, PALETTE_DAY, FISHGROUP_SHORE
	map_header_todo $25, $6005, TILESET_HOUSE_1, INDOOR, ROUTE_6, MUSIC_VERMILION_CITY, 0, PALETTE_DAY, FISHGROUP_SHORE
	map_header_todo $25, $6011, TILESET_MART, INDOOR, ROUTE_6, MUSIC_VERMILION_CITY, 0, PALETTE_DAY, FISHGROUP_SHORE
	map_header_todo $25, $601d, TILESET_HOUSE_1, INDOOR, ROUTE_6, MUSIC_VERMILION_CITY, 0, PALETTE_DAY, FISHGROUP_SHORE
	map_header_todo $25, $6029, TILESET_GAME_CORNER, INDOOR, ROUTE_6, MUSIC_GYM, 1, PALETTE_DAY, FISHGROUP_SHORE
	map_header_todo $25, $6035, TILESET_GATE, GATE, UNDERGROUND, MUSIC_ROUTE_3, 0, PALETTE_DAY, FISHGROUP_SHORE
	map_header_todo $25, $6041, TILESET_GATE, GATE, UNDERGROUND, MUSIC_ROUTE_3, 0, PALETTE_DAY, FISHGROUP_SHORE


MapGroup13:
	map_header_todo $25, $5345, TILESET_KANTO, ROUTE, PALLET_TOWN, MUSIC_ROUTE_1, 0, PALETTE_AUTO, FISHGROUP_SHORE
	map_header_todo $25, $5369, TILESET_KANTO, TOWN, SILVER_CAVE, MUSIC_PALLET_TOWN, 0, PALETTE_AUTO, FISHGROUP_OCEAN
	map_header_todo $25, $604d, TILESET_KRISS_HOUSE, INDOOR, SILVER_CAVE, MUSIC_PALLET_TOWN, 0, PALETTE_DAY, FISHGROUP_SHORE
	map_header_todo $25, $6059, TILESET_KRISS_HOUSE, INDOOR, SILVER_CAVE, MUSIC_PALLET_TOWN, 0, PALETTE_DAY, FISHGROUP_SHORE
	map_header_todo $25, $6065, TILESET_HOUSE_1, INDOOR, SILVER_CAVE, MUSIC_PALLET_TOWN, 0, PALETTE_DAY, FISHGROUP_SHORE
	map_header_todo $25, $6071, TILESET_LAB, INDOOR, SILVER_CAVE, MUSIC_POKEMON_TALK, 0, PALETTE_DAY, FISHGROUP_SHORE


MapGroup14:
	map_header_todo $25, $5735, TILESET_KANTO, ROUTE, PEWTER_CITY, MUSIC_ROUTE_3, 0, PALETTE_AUTO, FISHGROUP_SHORE
	map_header_todo $25, $52b5, TILESET_KANTO, TOWN, ROUTE_2, MUSIC_VIRIDIAN_CITY, 0, PALETTE_AUTO, FISHGROUP_SHORE
	map_header_todo $25, $607d, TILESET_HOUSE_1, INDOOR, ROUTE_2, MUSIC_VIRIDIAN_CITY, 0, PALETTE_DAY, FISHGROUP_SHORE
	map_header_todo $25, $6089, TILESET_SPROUT_TOWER, INDOOR, ROUTE_2, MUSIC_GYM, 1, PALETTE_DAY, FISHGROUP_SHORE
	map_header_todo $25, $6095, TILESET_MART, INDOOR, ROUTE_2, MUSIC_VIRIDIAN_CITY, 0, PALETTE_DAY, FISHGROUP_SHORE
	map_header_todo $25, $60a1, TILESET_POKECENTER, INDOOR, ROUTE_2, MUSIC_POKEMON_CENTER, 0, PALETTE_DAY, FISHGROUP_SHORE
	map_header_todo $25, $60ad, TILESET_POKECENTER, INDOOR, ROUTE_2, MUSIC_VIRIDIAN_CITY, 0, PALETTE_DAY, FISHGROUP_SHORE
	map_header_todo $25, $60b9, TILESET_HOUSE_1, INDOOR, ROUTE_2, MUSIC_VIRIDIAN_CITY, 0, PALETTE_DAY, FISHGROUP_SHORE


MapGroup15:
	map_header_todo $25, $60c5, TILESET_PORT, ROUTE, OLIVINE_CITY, MUSIC_VIOLET_CITY, 0, PALETTE_AUTO, FISHGROUP_OCEAN
	map_header_todo $25, $60d1, TILESET_PORT, ROUTE, ROUTE_6, MUSIC_VERMILION_CITY, 0, PALETTE_AUTO, FISHGROUP_OCEAN
	map_header_todo $25, $60dd, TILESET_LIGHTHOUSE, INDOOR, ROUTE_28, MUSIC_SS_AQUA, 0, PALETTE_DAY, FISHGROUP_SHORE
	map_header_todo $25, $60e9, TILESET_LIGHTHOUSE, INDOOR, ROUTE_28, MUSIC_SS_AQUA, 0, PALETTE_DAY, FISHGROUP_SHORE
	map_header_todo $25, $60f5, TILESET_LIGHTHOUSE, INDOOR, ROUTE_28, MUSIC_SS_AQUA, 0, PALETTE_DAY, FISHGROUP_SHORE
	map_header_todo $25, $6101, TILESET_LIGHTHOUSE, INDOOR, ROUTE_28, MUSIC_SS_AQUA, 0, PALETTE_DAY, FISHGROUP_SHORE
	map_header_todo $25, $610d, TILESET_LIGHTHOUSE, INDOOR, ROUTE_28, MUSIC_SS_AQUA, 0, PALETTE_DAY, FISHGROUP_SHORE
	map_header_todo $25, $6119, TILESET_UNDERGROUND, INDOOR, OLIVINE_CITY, MUSIC_VIOLET_CITY, 0, PALETTE_DAY, FISHGROUP_SHORE
	map_header_todo $25, $6125, TILESET_UNDERGROUND, INDOOR, ROUTE_6, MUSIC_VERMILION_CITY, 0, PALETTE_DAY, FISHGROUP_SHORE
	map_header_todo $25, $6131, TILESET_KANTO, ROUTE, ROUTE_3, MUSIC_MT_MOON_SQUARE, 0, PALETTE_AUTO, FISHGROUP_SHORE
	map_header_todo $25, $613d, TILESET_KURT_HOUSE, INDOOR, ROUTE_3, MUSIC_VIRIDIAN_CITY, 0, PALETTE_DAY, FISHGROUP_SHORE
	map_header_todo $25, $6149, TILESET_SPROUT_TOWER, ROUTE, TIN_TOWER, MUSIC_TIN_TOWER, 0, PALETTE_AUTO, FISHGROUP_SHORE


MapGroup16:
	map_header_todo $25, $57e9, TILESET_KANTO, TOWN, VICTORY_ROAD, MUSIC_INDIGO_PLATEAU, 0, PALETTE_AUTO, FISHGROUP_SHORE
	map_header_todo $25, $6155, TILESET_POKECENTER, INDOOR, ROUTE_23, MUSIC_INDIGO_PLATEAU, 0, PALETTE_DAY, FISHGROUP_SHORE
	map_header_todo $25, $6161, TILESET_GYM_1, INDOOR, ROUTE_23, MUSIC_INDIGO_PLATEAU, 1, PALETTE_DAY, FISHGROUP_SHORE
	map_header_todo $25, $616d, TILESET_GYM_1, INDOOR, ROUTE_23, MUSIC_INDIGO_PLATEAU, 1, PALETTE_DAY, FISHGROUP_SHORE
	map_header_todo $25, $6179, TILESET_GYM_1, INDOOR, ROUTE_23, MUSIC_INDIGO_PLATEAU, 1, PALETTE_DAY, FISHGROUP_SHORE
	map_header_todo $25, $6185, TILESET_GYM_1, INDOOR, ROUTE_23, MUSIC_INDIGO_PLATEAU, 1, PALETTE_DAY, FISHGROUP_SHORE
	map_header_todo $25, $6191, TILESET_OLIVINE_GYM, INDOOR, ROUTE_23, MUSIC_INDIGO_PLATEAU, 1, PALETTE_DAY, FISHGROUP_SHORE
	map_header_todo $25, $619d, TILESET_ICE_PATH, INDOOR, ROUTE_23, MUSIC_NEW_BARK_TOWN, 1, PALETTE_DAY, FISHGROUP_SHORE


MapGroup17:
	map_header_todo $25, $5549, TILESET_KANTO, ROUTE, ROUTE_12, MUSIC_ROUTE_12, 0, PALETTE_AUTO, FISHGROUP_QWILFISH_NO_SWARM
	map_header_todo $25, $5525, TILESET_KANTO, ROUTE, ROUTE_13, MUSIC_ROUTE_12, 0, PALETTE_AUTO, FISHGROUP_SHORE
	map_header_todo $25, $5501, TILESET_KANTO, ROUTE, ROUTE_14, MUSIC_ROUTE_12, 0, PALETTE_AUTO, FISHGROUP_SHORE
	map_header_todo $25, $544d, TILESET_KANTO, ROUTE, ROUTE_17, MUSIC_ROUTE_3, 0, PALETTE_AUTO, FISHGROUP_SHORE
	map_header_todo $25, $541d, TILESET_KANTO, TOWN, ROUTE_18, MUSIC_CELADON_CITY, 0, PALETTE_AUTO, FISHGROUP_GYARADOS
	map_header_todo $25, $61a9, TILESET_MART, INDOOR, ROUTE_18, MUSIC_CELADON_CITY, 0, PALETTE_DAY, FISHGROUP_SHORE
	map_header_todo $25, $61b5, TILESET_GAME_CORNER, INDOOR, ROUTE_18, MUSIC_CELADON_CITY, 0, PALETTE_DAY, FISHGROUP_SHORE
	map_header_todo $25, $61c1, TILESET_LAB, INDOOR, ROUTE_18, MUSIC_GYM, 1, PALETTE_DAY, FISHGROUP_SHORE
	map_header_todo $25, $61cd, TILESET_HOUSE_1, INDOOR, ROUTE_18, MUSIC_CELADON_CITY, 0, PALETTE_DAY, FISHGROUP_SHORE
	map_header_todo $25, $61d9, TILESET_POKECENTER, INDOOR, ROUTE_18, MUSIC_POKEMON_CENTER, 0, PALETTE_DAY, FISHGROUP_SHORE
	map_header_todo $25, $61e5, TILESET_POKECENTER, INDOOR, ROUTE_18, MUSIC_CELADON_CITY, 0, PALETTE_DAY, FISHGROUP_SHORE
	map_header_todo $25, $61f1, TILESET_HOUSE_1, INDOOR, ROUTE_18, MUSIC_CELADON_CITY, 0, PALETTE_DAY, FISHGROUP_SHORE
	map_header_todo $25, $61fd, TILESET_GATE, GATE, ROUTE_14, MUSIC_ROUTE_12, 0, PALETTE_DAY, FISHGROUP_SHORE


MapGroup18:
	map_header_todo $25, $577d, TILESET_KANTO, ROUTE, ROUTE_7, MUSIC_ROUTE_3, 0, PALETTE_AUTO, FISHGROUP_SHORE
	map_header_todo $25, $556d, TILESET_KANTO, ROUTE, ROUTE_11, MUSIC_ROUTE_12, 0, PALETTE_AUTO, FISHGROUP_QWILFISH_NO_SWARM
	map_header_todo $25, $57c5, TILESET_KANTO, ROUTE, ROCK_TUNNEL, MUSIC_ROUTE_3, 0, PALETTE_AUTO, FISHGROUP_LAKE
	map_header_todo $25, $55c1, TILESET_KANTO, TOWN, POWER_PLANT, MUSIC_LAVENDER_TOWN, 0, PALETTE_AUTO, FISHGROUP_SHORE
	map_header_todo $25, $6209, TILESET_POKECENTER, INDOOR, POWER_PLANT, MUSIC_POKEMON_CENTER, 0, PALETTE_DAY, FISHGROUP_SHORE
	map_header_todo $25, $6215, TILESET_POKECENTER, INDOOR, POWER_PLANT, MUSIC_POKEMON_CENTER, 0, PALETTE_DAY, FISHGROUP_SHORE
	map_header_todo $25, $6221, TILESET_HOUSE_1, INDOOR, POWER_PLANT, MUSIC_LAVENDER_TOWN, 0, PALETTE_DAY, FISHGROUP_SHORE
	map_header_todo $25, $622d, TILESET_HOUSE_1, INDOOR, POWER_PLANT, MUSIC_LAVENDER_TOWN, 0, PALETTE_DAY, FISHGROUP_SHORE
	map_header_todo $25, $6239, TILESET_HOUSE_1, INDOOR, POWER_PLANT, MUSIC_LAVENDER_TOWN, 0, PALETTE_DAY, FISHGROUP_SHORE
	map_header_todo $25, $6245, TILESET_MART, INDOOR, POWER_PLANT, MUSIC_LAVENDER_TOWN, 0, PALETTE_DAY, FISHGROUP_SHORE
	map_header_todo $25, $6251, TILESET_HOUSE_1, INDOOR, POWER_PLANT, MUSIC_LAVENDER_TOWN, 0, PALETTE_DAY, FISHGROUP_SHORE
	map_header_todo $25, $625d, TILESET_RADIO_TOWER, INDOOR, LAVENDER_TOWN, MUSIC_LAVENDER_TOWN, 0, PALETTE_DAY, FISHGROUP_SHORE
	map_header_todo $25, $6269, TILESET_GATE, GATE, ROUTE_7, MUSIC_ROUTE_3, 0, PALETTE_DAY, FISHGROUP_SHORE
	map_header_todo $25, $6275, TILESET_HOUSE_1, INDOOR, ROUTE_11, MUSIC_VIRIDIAN_CITY, 0, PALETTE_DAY, FISHGROUP_SHORE


MapGroup19:
	map_header_todo $25, $4ffd, TILESET_KANTO, ROUTE, TOHJO_FALLS, MUSIC_INDIGO_PLATEAU, 0, PALETTE_AUTO, FISHGROUP_POND
	map_header_todo $25, $4fa9, TILESET_KANTO, TOWN, ROUTE_46, MUSIC_INDIGO_PLATEAU, 0, PALETTE_AUTO, FISHGROUP_POND
	map_header_todo $25, $6281, TILESET_POKECENTER, INDOOR, ROUTE_46, MUSIC_POKEMON_CENTER, 0, PALETTE_DAY, FISHGROUP_SHORE
	map_header_todo $25, $628d, TILESET_HOUSE_1, INDOOR, TOHJO_FALLS, MUSIC_AZALEA_TOWN, 0, PALETTE_DAY, FISHGROUP_SHORE


MapGroup20:
	map_header_todo $25, $6299, TILESET_POKECENTER, INDOOR, SPECIAL_MAP, MUSIC_POKEMON_CENTER, 1, PALETTE_DAY, FISHGROUP_SHORE
	map_header_todo $25, $62a5, TILESET_GATE, INDOOR, SPECIAL_MAP, MUSIC_CHERRYGROVE_CITY, 1, PALETTE_DAY, FISHGROUP_SHORE
	map_header_todo $25, $62b1, TILESET_GATE, INDOOR, SPECIAL_MAP, MUSIC_CHERRYGROVE_CITY, 1, PALETTE_DAY, FISHGROUP_SHORE
	map_header_todo $25, $62bd, TILESET_GATE, INDOOR, SPECIAL_MAP, MUSIC_CHERRYGROVE_CITY, 1, PALETTE_DAY, FISHGROUP_SHORE


MapGroup21:
	map_header_todo $25, $54dd, TILESET_KANTO, ROUTE, DIGLETTS_CAVE, MUSIC_ROUTE_3, 0, PALETTE_AUTO, FISHGROUP_SHORE
	map_header_todo $25, $5495, TILESET_KANTO, ROUTE, ROUTE_15, MUSIC_ROUTE_3, 0, PALETTE_AUTO, FISHGROUP_SHORE
	map_header_todo $25, $5471, TILESET_KANTO, ROUTE, ROUTE_16, MUSIC_ROUTE_3, 0, PALETTE_AUTO, FISHGROUP_NONE
	map_header_todo $25, $54b9, TILESET_KANTO, TOWN, LAV_RADIO_TOWER, MUSIC_CELADON_CITY, 0, PALETTE_AUTO, FISHGROUP_NONE
	map_header_todo $25, $62c9, TILESET_MART, INDOOR, LAV_RADIO_TOWER, MUSIC_CELADON_CITY, 0, PALETTE_DAY, FISHGROUP_SHORE
	map_header_todo $25, $62d5, TILESET_MART, INDOOR, LAV_RADIO_TOWER, MUSIC_CELADON_CITY, 0, PALETTE_DAY, FISHGROUP_SHORE
	map_header_todo $25, $62e1, TILESET_MART, INDOOR, LAV_RADIO_TOWER, MUSIC_CELADON_CITY, 0, PALETTE_DAY, FISHGROUP_SHORE
	map_header_todo $25, $62ed, TILESET_MART, INDOOR, LAV_RADIO_TOWER, MUSIC_CELADON_CITY, 0, PALETTE_DAY, FISHGROUP_SHORE
	map_header_todo $25, $62f9, TILESET_MART, INDOOR, LAV_RADIO_TOWER, MUSIC_CELADON_CITY, 0, PALETTE_DAY, FISHGROUP_SHORE
	map_header_todo $25, $6305, TILESET_MART, INDOOR, LAV_RADIO_TOWER, MUSIC_CELADON_CITY, 0, PALETTE_DAY, FISHGROUP_SHORE
	map_header_todo $25, $6311, TILESET_MART, INDOOR, LAV_RADIO_TOWER, MUSIC_CELADON_CITY, 0, PALETTE_DAY, FISHGROUP_SHORE
	map_header_todo $25, $631d, TILESET_CELADON_MANSION, INDOOR, LAV_RADIO_TOWER, MUSIC_CELADON_CITY, 0, PALETTE_DAY, FISHGROUP_SHORE
	map_header_todo $25, $6329, TILESET_CELADON_MANSION, INDOOR, LAV_RADIO_TOWER, MUSIC_CELADON_CITY, 0, PALETTE_DAY, FISHGROUP_SHORE
	map_header_todo $25, $6335, TILESET_CELADON_MANSION, INDOOR, LAV_RADIO_TOWER, MUSIC_CELADON_CITY, 0, PALETTE_DAY, FISHGROUP_SHORE
	map_header_todo $25, $6341, TILESET_CELADON_MANSION, INDOOR, LAV_RADIO_TOWER, MUSIC_CELADON_CITY, 0, PALETTE_DAY, FISHGROUP_SHORE
	map_header_todo $25, $634d, TILESET_HOUSE_1, INDOOR, LAV_RADIO_TOWER, MUSIC_CELADON_CITY, 0, PALETTE_DAY, FISHGROUP_SHORE
	map_header_todo $25, $6359, TILESET_POKECENTER, INDOOR, LAV_RADIO_TOWER, MUSIC_POKEMON_CENTER, 0, PALETTE_DAY, FISHGROUP_SHORE
	map_header_todo $25, $6365, TILESET_POKECENTER, INDOOR, LAV_RADIO_TOWER, MUSIC_CELADON_CITY, 0, PALETTE_DAY, FISHGROUP_SHORE
	map_header_todo $25, $6371, TILESET_GAME_CORNER, INDOOR, LAV_RADIO_TOWER, MUSIC_GAME_CORNER, 0, PALETTE_DAY, FISHGROUP_SHORE
	map_header_todo $25, $637d, TILESET_GAME_CORNER, INDOOR, LAV_RADIO_TOWER, MUSIC_CELADON_CITY, 0, PALETTE_DAY, FISHGROUP_SHORE
	map_header_todo $25, $6389, TILESET_TRAIN_STATION, INDOOR, LAV_RADIO_TOWER, MUSIC_GYM, 1, PALETTE_DAY, FISHGROUP_SHORE
	map_header_todo $25, $6395, TILESET_GAME_CORNER, INDOOR, LAV_RADIO_TOWER, MUSIC_CELADON_CITY, 0, PALETTE_DAY, FISHGROUP_SHORE
	map_header_todo $25, $63a1, TILESET_HOUSE_1, INDOOR, ROUTE_15, MUSIC_CELADON_CITY, 0, PALETTE_DAY, FISHGROUP_SHORE
	map_header_todo $25, $63ad, TILESET_GATE, GATE, ROUTE_15, MUSIC_ROUTE_3, 0, PALETTE_DAY, FISHGROUP_SHORE
	map_header_todo $25, $63b9, TILESET_GATE, GATE, DIGLETTS_CAVE, MUSIC_ROUTE_3, 0, PALETTE_DAY, FISHGROUP_SHORE
	map_header_todo $25, $63c5, TILESET_GATE, GATE, ROUTE_16, MUSIC_ROUTE_3, 0, PALETTE_DAY, FISHGROUP_SHORE


MapGroup22:
	map_header_todo $25, $51b9, TILESET_JOHTO_1, ROUTE, BATTLE_TOWER, MUSIC_ROUTE_36, 0, PALETTE_AUTO, FISHGROUP_SHORE
	map_header_todo $25, $51dd, TILESET_JOHTO_1, ROUTE, WHIRL_ISLANDS, MUSIC_ROUTE_36, 0, PALETTE_AUTO, FISHGROUP_OCEAN
	map_header_todo $25, $4ead, TILESET_JOHTO_1, TOWN, ROUTE_41, MUSIC_ECRUTEAK_CITY, 0, PALETTE_AUTO, FISHGROUP_SHORE
	map_header_todo $25, $63d1, TILESET_HOUSE_1, INDOOR, ROUTE_41, MUSIC_ECRUTEAK_CITY, 0, PALETTE_DAY, FISHGROUP_SHORE
	map_header_todo $25, $63dd, TILESET_SPROUT_TOWER, INDOOR, ROUTE_41, MUSIC_GYM, 1, PALETTE_DAY, FISHGROUP_SHORE
	map_header_todo $25, $63e9, TILESET_POKECENTER, INDOOR, ROUTE_41, MUSIC_POKEMON_CENTER, 0, PALETTE_DAY, FISHGROUP_SHORE
	map_header_todo $25, $63f5, TILESET_HOUSE_1, INDOOR, ROUTE_41, MUSIC_ECRUTEAK_CITY, 0, PALETTE_DAY, FISHGROUP_SHORE
	map_header_todo $25, $6401, TILESET_HOUSE_1, INDOOR, ROUTE_41, MUSIC_ECRUTEAK_CITY, 0, PALETTE_DAY, FISHGROUP_SHORE
	map_header_todo $25, $640d, TILESET_HOUSE_1, INDOOR, ROUTE_41, MUSIC_ECRUTEAK_CITY, 0, PALETTE_DAY, FISHGROUP_SHORE


MapGroup23:
	map_header_todo $25, $52d9, TILESET_KANTO, ROUTE, VIRIDIAN_CITY, MUSIC_ROUTE_2, 0, PALETTE_AUTO, FISHGROUP_SHORE
	map_header_todo $25, $532d, TILESET_KANTO, ROUTE, ROUTE_21, MUSIC_ROUTE_3, 0, PALETTE_AUTO, FISHGROUP_POND
	map_header_todo $25, $52fd, TILESET_KANTO, TOWN, ROUTE_1, MUSIC_VIRIDIAN_CITY, 0, PALETTE_AUTO, FISHGROUP_POND
	map_header_todo $25, $6419, TILESET_TRAIN_STATION, INDOOR, ROUTE_1, MUSIC_GYM, 1, PALETTE_DAY, FISHGROUP_SHORE
	map_header_todo $25, $6425, TILESET_HOUSE_1, INDOOR, ROUTE_1, MUSIC_VIRIDIAN_CITY, 0, PALETTE_DAY, FISHGROUP_SHORE
	map_header_todo $25, $6431, TILESET_HOUSE_1, INDOOR, ROUTE_1, MUSIC_VIRIDIAN_CITY, 0, PALETTE_DAY, FISHGROUP_SHORE
	map_header_todo $25, $643d, TILESET_POWER_PLANT, INDOOR, ROUTE_1, MUSIC_VIRIDIAN_CITY, 0, PALETTE_DAY, FISHGROUP_SHORE
	map_header_todo $25, $6449, TILESET_MART, INDOOR, ROUTE_1, MUSIC_VIRIDIAN_CITY, 0, PALETTE_DAY, FISHGROUP_SHORE
	map_header_todo $25, $6455, TILESET_POKECENTER, INDOOR, ROUTE_1, MUSIC_POKEMON_CENTER, 0, PALETTE_DAY, FISHGROUP_SHORE
	map_header_todo $25, $6461, TILESET_POKECENTER, INDOOR, ROUTE_1, MUSIC_VIRIDIAN_CITY, 0, PALETTE_DAY, FISHGROUP_SHORE
	map_header_todo $25, $646d, TILESET_HOUSE_1, INDOOR, VIRIDIAN_CITY, MUSIC_VIRIDIAN_CITY, 0, PALETTE_DAY, FISHGROUP_SHORE
	map_header_todo $25, $6479, TILESET_GATE, GATE, VIRIDIAN_CITY, MUSIC_ROUTE_2, 0, PALETTE_DAY, FISHGROUP_SHORE
	map_header_todo $25, $6485, TILESET_GATE, GATE, INDIGO_PLATEAU, MUSIC_INDIGO_PLATEAU, 0, PALETTE_DAY, FISHGROUP_SHORE


MapGroup24:
	map_header_todo $25, $4fc1, TILESET_JOHTO_1, ROUTE, INDIGO_PLATEAU, MUSIC_ROUTE_26, 0, PALETTE_AUTO, FISHGROUP_OCEAN
	map_header_todo $25, $4fd9, TILESET_JOHTO_1, ROUTE, ROUTE_26, MUSIC_ROUTE_26, 0, PALETTE_AUTO, FISHGROUP_OCEAN
	map_header_todo $25, $5015, TILESET_JOHTO_1, ROUTE, ROUTE_29, MUSIC_ROUTE_29, 0, PALETTE_AUTO, FISHGROUP_SHORE
	map_header_todo $25, $4e11, TILESET_JOHTO_1, TOWN, NEW_BARK_TOWN, MUSIC_NEW_BARK_TOWN, 0, PALETTE_AUTO, FISHGROUP_OCEAN
	map_header_todo $25, $6491, TILESET_LAB, INDOOR, NEW_BARK_TOWN, MUSIC_PROF_ELM, 0, PALETTE_DAY, FISHGROUP_SHORE
	map_header_todo $25, $649d, TILESET_KRISS_HOUSE, INDOOR, NEW_BARK_TOWN, MUSIC_NEW_BARK_TOWN, 0, PALETTE_DAY, FISHGROUP_SHORE
	map_header_todo $25, $64a9, TILESET_KRISS_HOUSE_2F, INDOOR, NEW_BARK_TOWN, MUSIC_NEW_BARK_TOWN, 0, PALETTE_DAY, FISHGROUP_SHORE
	map_header_todo $25, $64b5, TILESET_HOUSE_1, INDOOR, NEW_BARK_TOWN, MUSIC_NEW_BARK_TOWN, 0, PALETTE_DAY, FISHGROUP_SHORE
	map_header_todo $25, $64c1, TILESET_KRISS_HOUSE, INDOOR, NEW_BARK_TOWN, MUSIC_NEW_BARK_TOWN, 0, PALETTE_DAY, FISHGROUP_SHORE
	map_header_todo $25, $64cd, TILESET_HOUSE_1, INDOOR, INDIGO_PLATEAU, MUSIC_AZALEA_TOWN, 0, PALETTE_DAY, FISHGROUP_SHORE
	map_header_todo $25, $64d9, TILESET_HOUSE_1, INDOOR, INDIGO_PLATEAU, MUSIC_AZALEA_TOWN, 0, PALETTE_DAY, FISHGROUP_SHORE
	map_header_todo $25, $64e5, TILESET_HOUSE_1, INDOOR, ROUTE_26, MUSIC_AZALEA_TOWN, 0, PALETTE_DAY, FISHGROUP_SHORE
	map_header_todo $25, $64f1, TILESET_GATE, GATE, ROUTE_29, MUSIC_ROUTE_29, 0, PALETTE_DAY, FISHGROUP_SHORE


MapGroup25:
	map_header_todo $25, $5675, TILESET_KANTO, ROUTE, ROUTE_25, MUSIC_ROUTE_3, 0, PALETTE_AUTO, FISHGROUP_SHORE
	map_header_todo $25, $5639, TILESET_KANTO, TOWN, CELADON_CITY, MUSIC_VIRIDIAN_CITY, 0, PALETTE_AUTO, FISHGROUP_SHORE
	map_header_todo $25, $64fd, TILESET_TRAIN_STATION, INDOOR, CELADON_CITY, MUSIC_VIRIDIAN_CITY, 0, PALETTE_DAY, FISHGROUP_SHORE
	map_header_todo $25, $6509, TILESET_UNDERGROUND, INDOOR, CELADON_CITY, MUSIC_GYM, 1, PALETTE_DAY, FISHGROUP_SHORE
	map_header_todo $25, $6515, TILESET_MART, INDOOR, CELADON_CITY, MUSIC_VIRIDIAN_CITY, 0, PALETTE_DAY, FISHGROUP_SHORE
	map_header_todo $25, $6521, TILESET_POKECENTER, INDOOR, CELADON_CITY, MUSIC_POKEMON_CENTER, 0, PALETTE_DAY, FISHGROUP_SHORE
	map_header_todo $25, $652d, TILESET_POKECENTER, INDOOR, CELADON_CITY, MUSIC_VIRIDIAN_CITY, 0, PALETTE_DAY, FISHGROUP_SHORE
	map_header_todo $25, $6539, TILESET_HOUSE_1, INDOOR, CELADON_CITY, MUSIC_VIRIDIAN_CITY, 0, PALETTE_DAY, FISHGROUP_SHORE
	map_header_todo $25, $6545, TILESET_TRAIN_STATION, INDOOR, CELADON_CITY, MUSIC_VIRIDIAN_CITY, 0, PALETTE_DAY, FISHGROUP_SHORE
	map_header_todo $25, $6551, TILESET_POWER_PLANT, INDOOR, CELADON_CITY, MUSIC_VIRIDIAN_CITY, 0, PALETTE_DAY, FISHGROUP_SHORE
	map_header_todo $25, $655d, TILESET_KRISS_HOUSE, INDOOR, CELADON_CITY, MUSIC_VIRIDIAN_CITY, 0, PALETTE_DAY, FISHGROUP_SHORE
	map_header_todo $25, $6569, TILESET_KRISS_HOUSE, INDOOR, CELADON_CITY, MUSIC_VIRIDIAN_CITY, 0, PALETTE_DAY, FISHGROUP_SHORE
	map_header_todo $25, $6575, TILESET_GATE, GATE, ROUTE_25, MUSIC_ROUTE_3, 0, PALETTE_DAY, FISHGROUP_SHORE
	map_header_todo $25, $6581, TILESET_GATE, GATE, ROUTE_25, MUSIC_VIRIDIAN_CITY, 0, PALETTE_DAY, FISHGROUP_SHORE
	map_header_todo $25, $658d, TILESET_HOUSE_1, INDOOR, ROUTE_25, MUSIC_VIRIDIAN_CITY, 0, PALETTE_DAY, FISHGROUP_SHORE


MapGroup26:
	map_header_todo $25, $5045, TILESET_JOHTO_1, ROUTE, ROUTE_30, MUSIC_ROUTE_30, 0, PALETTE_AUTO, FISHGROUP_POND
	map_header_todo $25, $5069, TILESET_JOHTO_1, ROUTE, ROUTE_31, MUSIC_ROUTE_30, 0, PALETTE_AUTO, FISHGROUP_POND
	map_header_todo $25, $4e35, TILESET_JOHTO_1, TOWN, CHERRYGROVE_CITY, MUSIC_CHERRYGROVE_CITY, 0, PALETTE_AUTO, FISHGROUP_SHORE
	map_header_todo $25, $6599, TILESET_MART, INDOOR, CHERRYGROVE_CITY, MUSIC_CHERRYGROVE_CITY, 0, PALETTE_DAY, FISHGROUP_SHORE
	map_header_todo $25, $65a5, TILESET_POKECENTER, INDOOR, CHERRYGROVE_CITY, MUSIC_POKEMON_CENTER, 0, PALETTE_DAY, FISHGROUP_SHORE
	map_header_todo $25, $65b1, TILESET_HOUSE_1, INDOOR, CHERRYGROVE_CITY, MUSIC_CHERRYGROVE_CITY, 0, PALETTE_DAY, FISHGROUP_SHORE
	map_header_todo $25, $65bd, TILESET_HOUSE_1, INDOOR, CHERRYGROVE_CITY, MUSIC_CHERRYGROVE_CITY, 0, PALETTE_DAY, FISHGROUP_SHORE
	map_header_todo $25, $65c9, TILESET_HOUSE_1, INDOOR, CHERRYGROVE_CITY, MUSIC_CHERRYGROVE_CITY, 0, PALETTE_DAY, FISHGROUP_SHORE
	map_header_todo $25, $65d5, TILESET_HOUSE_1, INDOOR, ROUTE_30, MUSIC_CHERRYGROVE_CITY, 0, PALETTE_DAY, FISHGROUP_SHORE
	map_header_todo $25, $65e1, TILESET_POWER_PLANT, INDOOR, ROUTE_30, MUSIC_CHERRYGROVE_CITY, 0, PALETTE_DAY, FISHGROUP_SHORE
	map_header_todo $25, $65ed, TILESET_GATE, GATE, ROUTE_31, MUSIC_ROUTE_30, 0, PALETTE_DAY, FISHGROUP_SHORE

	dr $94e11, $95b6d
